### ISSUE TITLE
Feature request: Accepted answer should appear before not accepted one with the same number of votes when answer are sorted by votes..

### ISSUE THREAD

**Issue by fathzer** [Erudika/scoold#10]
If a question has two replies. Most recent is accepted by the question's author. None have any vote.
When answer are sorted by votes, the accepted answer appears after the other answer (which is probably less interesting).
Would it be possible to sort by votes and accepted if votes are equals?
Tested on Tested on scoold 1.25.4.
![image](https://user-images.githubusercontent.com/1562721/30754216-377e988e-9fc2-11e7-8a3b-c2b2d2921a82.png)

**Comment by albogdano** [comment]
I'm not in favor of adding another button for sorting, perhaps it's best if the accepted answer is always on top when sorting by votes?

**Comment by fathzer** [comment]
I completely agree. It seems it is the way Stackoverflow works :-)

**Comment by albogdano** [comment]
I was thinking about this... sometimes the accepted answer is not very useful and another answer below it has more points, maybe we should show the accepted answer first, *only* if it has >= (the points of the next one) + 5. Thus, if an answer is accepted early, but later we get a much better one that has +5 more points than the accepted answer, we show that new, better answer at the top. Does this make sense? 
And, yes, in the case you showed above, the accepted one will be on top.
