### ISSUE TITLE
Unanswered filter

### ISSUE THREAD

**Issue by fisettec** [Erudika/scoold#102]
Feature request for the unanswered filter: it's sometime useful to see the questions without approved answers. Even if a question is answered, it doesn't mean that the provided answer is pertinent or to the point. So a question with answers but w/o approved answer may still be considered unanswered by its owner. 

It would be best that the unanswered filter work as Stackexchange; in that case only questions with no upvoted or accepted answers are shown.

**Comment by albogdano** [comment]
Thanks for the suggestion @fisettec! I'll try to implement this for the next release. As a workaround you could try typing `type:question AND NOT answerid` in the search box.
