### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by sils** [Erudika/scoold#104]
Like the tool, however I feel like in order for us to use this we need to have webhooks that notify people on slack/mattermost about new questions so people actually get drawn to our scoold instance.

We'd probably need to write sth like https://github.com/Erudika/scoold/blob/master/src/main/java/com/erudika/scoold/controllers/QuestionController.java#L308 that then sends our webhooks.

**Comment by albogdano** [comment]
That's a good idea! I'm thinking, maybe it's better to implement webhooks on the backend (Para) for create/update/delete methods. Then Scoold will register a webhook with Para for objects of type `question` and method `POST`, for example. What do you think?

**Comment by rafik777** [comment]
@albogdano Is there a chance to implement this feature in near future?

**Comment by albogdano** [comment]
I can't say exactly when this will be implemented but I hope to get it done in a couple of months time.

**Comment by albogdano** [comment]
@sils @rafik777 I'm working on this now. Should be done in a couple of days time.
