### ISSUE TITLE
How do I set multiple MS admins?

### ISSUE THREAD

**Issue by bviktor** [Erudika/scoold#105]
If I set

```
para.admins = "viktor.b@foobar.com"
```

It works. Then if I set:

```
para.admins = "viktor.b@foobar.com,david.b@foomotive.com"
```

Then David stays user and I'm demoted too.

**Comment by albogdano** [comment]
This feature is implemented in Scoold Pro. You can only have one admin in the open source version.

**Comment by bviktor** [comment]
Ah, indeed it's mentioned in the readme, sorry!
