### ISSUE TITLE
Voting is horribly broken

### ISSUE THREAD

**Issue by bviktor** [Erudika/scoold#107]
- Users can downvote multiple times, thus a +2 (or more?) question can become 0 by a single user. Seems like the UI allows upvoting once then downvoting twice, till it reaches -1.
- Then if I reload the page, it's on 1(???). Then you can only downvote it till 0.
- Voting seems to happen client-side e.g. user A loads question, answer is on 0, user B adds +1 to it, so it's on +1 now, but user A doesn't reload the screen and +1 it and it stays on +1 while it should be +2 now. It feels like the client tells the server "I see 0, I add +1, so please make it +1 now" instead of saying "Please add +1 to whatever its current value is".
- Users can't seem to change their vote (might be related to the bugs above messing up the db)
- I don't know how reputation is calculated, but now my rep is 34 with a +2 question and -1 answer. Other user has one answer with 0 vote atm and his rep is 67. This value seems odd.

And the worst part of it is that I can't reliably reproduce any of the above.

**Comment by albogdano** [comment]
Voting happens on the serverside and is handled by Para. What you're seeing is probably a JS bug on the clientside. I'll investigate it.

**Comment by bviktor** [comment]
Thanks, will try to re-test next week!

**Comment by albogdano** [comment]
Indeed, there was a problem with voting. I think it should work as expected now. Votes can be amended within 60 seconds of the first vote request. Reputation points were rewarded incorrectly and that's the reason why you got those strange reputation values. 

Thanks for reporting this!

**Comment by bviktor** [comment]
Unfortunately this has been postponed to next week for us.

Btw. what do you think of making this 60 seconds configurable?

**Comment by albogdano** [comment]
Actually it's not 60s but 30s by default and it is configurable but only for Para at the moment. Set `para.vote_locked_after = 30` (goes inside the Para config file) and change 30 to whatever seconds you want.

**Comment by bviktor** [comment]
Thanks! By "Para config file" you mean Scoold's config or Para's? I'm asking coz it's weird if I have to change Para's config for something that's managed by Scoold.

**Comment by albogdano** [comment]
Yes, I meant Para's config file. As I mentioned previously, almost everything is handled by Para, including voting requests.
