### ISSUE TITLE
feature request: soft-delete resources

### ISSUE THREAD

**Issue by weisjohn** [Erudika/scoold#108]
Is there any way to configure the app to allow soft-deleting of resources?

**Comment by albogdano** [comment]
By resources you mean questions and answers? This is not implemented yet.
If I understand correctly, soft-deleting a question will mark it as
"archived" but won't actually delete it. It will remain hidden from the
list of question but be visible only to admins.

**Comment by mirt001** [comment]
I am not sure what is the status of this feature, but I would find it useful.

**Comment by albogdano** [comment]
This is currently very a low priority feature. What is the point of archiving posts if they can be deleted?
