### ISSUE TITLE
Microsoft avatars randomly missing

### ISSUE THREAD

**Issue by bviktor** [Erudika/scoold#110]
As you mentioned earlier, they're indeed missing randomly. Randomly as in, I couldn't find a pattern yet.

I don't see anything relevant in the logs.

**Comment by albogdano** [comment]
What I mentioned before had nothing to do with Microsoft logins. It was an issue with the `SameSite` cookie flag being set to `strict` instead of `lax`. Microsoft avatars are stored as Base64-encoded data `data:image/jpeg;...` directly inside the database. If for example the avatar is too large, you may be hitting a limit in the database for column size or something.

**Comment by bviktor** [comment]
I doubt that to be the case. My avatar was downloaded fine, it's 20.2 kB and 504x504 pixels. My coworker's avatar is 11.8 kB and 120x120 pixels, yet it failed to download.

If I click on "change picture", for me it's `data:image...` and Gravatar is turned off, for those whose is missing it's a Gravatar URL (even though they don't have Gravatar) and Gravatar is on for the Scoold account.

How do I track this down?

**Comment by bviktor** [comment]
Uh, it's actually getting worse: I merely clicked on "Change picture", I didn't click on anything else, and on a separate tab my avatar already disappeared. After a refresh, it's gone from everywhere lol. Now it's set to Gravarar for me too, even though I didn't make any changes.

**Comment by bviktor** [comment]
For that matter, shouldn't avatar changes be disabled for external accounts, like Microsoft? We've been having a hard time preventing users from setting their avatars to goats and the like (yeah, immature). So we ended up disabling avatar changes altogether, and now only admins can upload pictures via PowerShell.

Regardless, I think if the credentials are managed centrally, so should be the avatars, so changes shouldn't be allowed.

But that's not the main issue here, the bigger one is that they're missing for around 80% of our users :D

**Comment by bviktor** [comment]
So I tried to simply enter the base64 string as my avatar. Then it changes it in the top right corner immediately, but not on the profile page itself.

If I simply navigate away after pasting the string, the avatar is gone from the top right, and when I open my profile page again, it's the gravatar URL again.

If I press Return in the input field after pasting the base64 string, (as there's no Save button or anything), I get this error:

```
Critical server error.
500 org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.InternalError: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/ext/dnsns.jar 
```

**Comment by bviktor** [comment]
One more bug :D While trying to click on the "Change picture" button for other users, ONCE the other user's avatar appeared in the top right as if it was my picture. When I navigated away, it disappeared and I got the placeholder pic again.

I couldn't reproduce it again lol.

**Comment by albogdano** [comment]
Thanks for reporting these, I'll have a go at fixing them later today. I suppose we could have an option like `para.avatar_edits_enabled = false` to disable editing of avatars altogether.

**Comment by bviktor** [comment]
Sounds good!

**Comment by bviktor** [comment]
Thanks, the new option works, but the issue of missing avatars has not been resolved at all, so I'm not sure why you closed this one.

**Comment by albogdano** [comment]
I've updated Para to load avatars from the correct URL now (see [last commit](https://github.com/Erudika/para/commit/2397a619b30d78817503d661628d1882c69b497b)). Hopefully that was the reason why some avatars were not loaded properly. Eventually, when you update Para, the issue should be resolved. If it's not, I'll reopen the issue.
