### ISSUE TITLE
Cannot assign users to spaces

### ISSUE THREAD

**Issue by fnielsontestout** [Erudika/scoold#111]
I've set up a local scoold server with para running in the background. The scoold server is version 1.31.2.
I have myself as an admin and a few other users for testing purposes and I've created 2 other spaces.

As an admin, I can see all 3 spaces (default space, plus the 2 other ones), but when I log into the test user account, I can't see the other spaces.

When logged in as an admin, I see no way to assign a user to a space(s).

**Comment by albogdano** [comment]
Only admins can see all spaces. Regular users can only see the spaces they
have been assigned to. To assign people to spaces, go to the People section
and click the button 'assign to spaces' (you have to be admin to do that).

**Comment by fnielsontestout** [comment]
Ah. I see the "bulk edit spaces" now. Is there a way I can assign them to the default space as well?
![image](https://user-images.githubusercontent.com/48336978/54032886-15d60180-4170-11e9-9211-b0c73c82555c.png)

**Comment by albogdano** [comment]
The default space is assigned to everyone automatically. It may be public
or private - check the Readme.md for details.

**Comment by fnielsontestout** [comment]
True. But once I assign them to one or more spaces, then they cannot see the default space anymore:
![image](https://user-images.githubusercontent.com/48336978/54038172-1f199b00-417d-11e9-953a-f686ef0746c9.png)

![image](https://user-images.githubusercontent.com/48336978/54038244-45d7d180-417d-11e9-9bbc-d9109d2f7bf4.png)

**Comment by albogdano** [comment]
I see. What's the value of `para.is_default_space_public` in your configuration? If it's `false` then the default space is private. As a matter of fact the default space isn't really a space as such. It simply means that these users are not assigned to any space. It's not a real space and doesn't have an identifier.

**Comment by fnielsontestout** [comment]
It is set to false since I don't want non-logged in users to be able to view it. But I do want people to be able to see it in case their question isn't answered on the other spaces.
I guess a good question is to ask if they can choose to search for questions on any space, and not just the ones that they have access to (I'm not certain that's a good feature for everyone, but in my case, it would work out).


________________________________

**Comment by albogdano** [comment]
You can search for questions within the selected space only. Spaces are isolated so you won't see any results from a space you don't belong to. 
I'm not sure why anyone would ask the same question in several different spaces, but I think the use case you need is not exactly supported.

**Comment by fnielsontestout** [comment]
In my case, it's because people within the company have some overlap in the technologies used. I could have one big space to cover all the teams with similar technology, but there would be more non-applicable questions in the same space from other teams.


I'll just have the spaces "bigger" than I realized.


Thank you

________________________________
