### ISSUE TITLE
User name change not saved with OpenID identity provider

### ISSUE THREAD

**Issue by dave08** [Erudika/scoold#114]
I have only OpenID + Keycloak, with no other user creation possibilities. When on the edit profile page, I try changing the name and saving it, it shows that it was saved, but the name didn't change neither in Para nor in Keycloak. Also, when changing the name in Keycloak, the change is not reflected in Scoold.

**Comment by albogdano** [comment]
The user object in Para is of type `user` and Scoold has it's own user `profile` object where names are saved. This allows Scoold users to change their name independently of what's stored by the authentication provider. If we overwrite the `profile` name on each login, then name editing will be pointless and should be disabled. Also the sync will work in one direction only - from identity provider to Para `user`, to Scoold `profile`.
I'm thinking it would be best to allow the names to be synced and disable name edits in Scoold by default for OpenID/OAuth logins, but also have a new config property `para.name_edits_enabled`.

**Comment by dave08** [comment]
Maybe the name could not be = to the name in the identity provider, since often a user doesn't want to show his/her real name when posting, whereas admins should possibly be able to see the real name? So the profile name could be a type of display name that is by default copied from the identity's name.

That aside idea of a one way sync would make sense, but name_edits_enabled would make more sense for the concept of a display name, unless there would be a way to set the name in the identity provider (if allowed...).
