### ISSUE TITLE
OpenID logout doesn't seem to logout from Keycloak

### ISSUE THREAD

**Issue by dave08** [Erudika/scoold#115]
When logging out from Scoold, I get the "continue with OpenID" button, but it doesn't redirect me to Keycloak's login page, but rather just goes in to Scoold with the previous account logged in with.

I don't know if this is the normal behaviour (maybe not Scoold's fault?), but it is a bit unexpected... what's the point of logging out then?

**Comment by albogdano** [comment]
This is normal behavior. Neither Scoold nor Para will logout a user from an identity provider like Keycloak (global logout). This is just not implemented. Scoold has its own session (24 hours by default). This is configurable - `para.session_timeout = 86400`.
