### ISSUE TITLE
Beginner question: Getting Started with Scoold

### ISSUE THREAD

**Issue by slemkemeier** [Erudika/scoold#12]
Hi! I am trying to set up Scoold locally. I have created an app on ParaIO.com, cloned the repo, and configured my application.conf file, but when I try to run it I receive the following warning: "Para configuration file 'application.(conf|json|properties)' is missing from classpath". My config file is in the same folder as the jar (/target), and I have also tried putting it in the main folder, but nothing seems to work. Suggestions? Thanks so much!

**Comment by albogdano** [comment]
Hi @slemkemeier, try running this from the command line:
```java -jar -Dserver.port=8000 -Dconfig.file=./application.conf scoold.jar```
You might be missing that `-Dconfig.file` argument.

**Comment by slemkemeier** [comment]
I have been running it with the -Dconfig.file argument, but continue to get the same warning. Any other suggestions?

**Comment by albogdano** [comment]
Your config syntax is probably incorrect. Try with an empty config file and if the message goes away, you have a syntax error.

**Comment by slemkemeier** [comment]
It worked!!! Thank you so much, that's a huge help!!
