### ISSUE TITLE
Missing questions in default space after update to 1.32.1, only visible to admin users

### ISSUE THREAD

**Issue by albogdano** [Erudika/scoold#120]
This is an explanation and a solution to the problem of missing questions after an update to `1.32.1`.

Previously, everyone in the default space could see questions posted in other spaces but couldn't access those. This was an unpleasant bug which is now fixed. The side effect of that fix is that all your questions don't have any space assigned and hence appear hidden. Having a blank space value for a question used to mean that it's in the default space but now this must be explicitly set. 

**The way to solve this is to login as admin, clear the `postviews` cookie and visit every question.**  This will update the view count but also set the default space to `scooldspace:default` on each question object. Eventually all questions will be visible to your regular users.

**Comment by soster** [comment]
I use the dockerized version and after an update to 1.32.2, I do not see any questions or users anymore. Login works with the old accounts, but the described solution here is not working for me. Any other possibility?

**Comment by albogdano** [comment]
There's no other workaround than to read each question object and update it. Before 1.32.1 the objects had `space: ""` or `space: null`, now they must have a value like `space: "scooldspace:default"` in order to be visible.

**Comment by soster** [comment]
Can I do that somehow in the h2 database directly? As I said, the trick with the admin user is not working, the questions are not showing up.

**Comment by albogdano** [comment]
If you are admin you should be seeing all questions no matter what. Are you sure you're in the default space? 
I guess you could do a mass update with an SQL command but I'm not sure how. You need to change just a single field in a column containing a JSON string.

**Comment by soster** [comment]
I could solve it this way:
* Get the database file from the server and locally start a h2 server with this file
* Connect to the server with the h2 server webinterface
* Use this select statement: `select * from para_scoold where type='question';`
* Copy the ID of each question
* Use this url: /question/[id]/some-text
* set the namespace for the question. Sometimes this is not working, then you can add a comment to the question
