### ISSUE TITLE
Mail URL redirects to localhost

### ISSUE THREAD

**Issue by a-durst** [Erudika/scoold#123]
when I get a mail from the scoold instance on our server, the url to the question is always starting with localhost:8080 instead of the set url.

Version: scoold pro 1.33.0
Para: 1.33.0

para.host_url = "http://knowledge"
this url will be redirected by nginx to "https://knowledge:8443"

**Comment by albogdano** [comment]
This is probably because you have `para.env = "development"`. Set it to "production" and `para.host_url` will work as expected.
