### ISSUE TITLE
OAuth 2.0 issue with jwt in URL Scoold 1.33.1

### ISSUE THREAD

**Issue by susverwimp** [Erudika/scoold#124]
I have a problem signing in with my custom OAuth2.0 provider

I have created a Para instance like in the tutorial, where I have the root application and 1 child application, which is the app:scoold application.

I have configured scoold with the default configuration + the following
```
# minimal setup
para.oa2_app_id = "clientid"
para.oa2_secret = "clientSecret"
para.security.oauth.authz_url = "https://local.honeur.org:43211/cas/oauth2.0/authorize"
para.security.oauth.token_url = "https://local.honeur.org:43211/cas/oauth2.0/accessToken"
para.security.oauth.profile_url = "https://local.honeur.org:43211/cas/oauth2.0/profile"

para.security.oauth.parameters.id = "id"

# Sets the string on the login button
para.security.oauth.provider = "CAS Oauth Server"

# Enable/disable access token delegation
para.security.oauth.token_delegation_enabled = true
```

When I try to authenticate, Scoold is trying to get a authentication code from the OAuth2.0 provider with the following GET Request:

https://<OAuth Provider>/oauth2.0/authorize?response_type=code&client_id=clientid&scope=&state=scoold&redirect_uri=http://forum.honeur.org:43218/oauth2_auth

This call redirects me to the Para server:
http://<Para Server>/oauth2_auth?code=OC-107-lgHDkyW5MsXXIGrhCzSJ9y-ZW88YlHyi&state=scoold

This call will generate a JWT and then redirects me to the SIGNIN_SUCCESS URL with the JWT attached as a parameter.
This call also creates a para-auth COOKIE because the rememberMe is always on by default. This cookie is not the JWT:

http://<Scoold Forum>/signin/success?jwt=<CORRECT JWT>

When this call is being executed, The following code is called to check the authentication:

```
public ParaObject checkAuth(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
	Profile authUser = null;
	boolean isApiRequest = isApiRequest(req);
	if (isApiRequest) {
		return checkApiAuth(req);
	} else if (HttpUtils.getStateParam(Config.AUTH_COOKIE, req) != null && !StringUtils.endsWithAny(req.getRequestURI(), ".js", ".css", ".svg", ".png", ".jpg")) {
//		String test = req.getParameter("jwt");
//		if (test == null) {
//			test = HttpUtils.getStateParam(Config.AUTH_COOKIE, req);
//		}
		String test = HttpUtils.getStateParam(Config.AUTH_COOKIE, req);
		User u = pc.me(test);
		if (u != null && isEmailDomainApproved(u.getEmail())) {
			authUser = getOrCreateProfile(u, req);
			authUser.setUser(u);
			if (promoteOrDemoteUser(authUser, u) || updateProfilePictureAndName(authUser, u)) {
				authUser.update();
			}
		} else {
			clearSession(req, res);
			if (u != null) {
				logger.warn("Attempted signin from an unknown domain: {}", u.getEmail());
			} else {
				logger.info("Invalid JWT found in cookie {}.", Config.AUTH_COOKIE);
			}
			res.sendRedirect(SIGNINLINK + "?code=3&error=true");
			return null;
		}
	}
	if (!isApiRequest) {
		initCSRFToken(req, res);
	}
	return authUser;
}
```

The commented code is custom. I need to check if the url contains a parameter JWT(which is appended in the previous call) instead of just looking at the value in the Cookie "para-auth".
When I uncomment this code, the whole system works and I can authenticate with my OAuth2.0 provider. But when I comment out this piece of code, I get a Runtime error saying that the value inside the "para-auth" COOKIE is not a JWT.

My question is if I'm missing some configuration to make this work?

Thanks in advance.

**Comment by albogdano** [comment]
Perhaps what you're missing is `para.app_name = "Scoold"` in Scoold's config file. The name of the auth cookie for Scoold is usually `scoold-auth`. Also you can check the `jwt` query parameter in `SigninController` line 107.

**Comment by susverwimp** [comment]
I solved this error by turning off the remember me functionality when logging in. This is hard coded in the `SecurityModule` line 137
```java
@Provides
public SimpleRememberMeServices getRemembeMeServices() {
	if (rememberMeServices == null) {
		rememberMeServices = new SimpleRememberMeServices(Config.APP_SECRET_KEY, new SimpleUserService());
		rememberMeServices.setAlwaysRemember(false);
		rememberMeServices.setTokenValiditySeconds(Config.SESSION_TIMEOUT_SEC);
		rememberMeServices.setCookieName(Config.AUTH_COOKIE);
		rememberMeServices.setParameter(Config.AUTH_COOKIE.concat("-remember-me"));

		}
	return rememberMeServices;
}
```
It was this filter that overwrote the correct JWT in the authentication cookie with an other value when logging in.

**Comment by albogdano** [comment]
Thanks for the update. I'll probably add a configuration flag to turn this
off when needed.
