### ISSUE TITLE
instructions for docker stack deploy?

### ISSUE THREAD

**Issue by kaeverens** [Erudika/scoold#129]
With the current docker instructions, the para server is exposed to public access through a non-secure HTTP connection. I don't know enough to adjust the docker-compose.yml file to allow the service to be deployed such that the para server is within a local network not-accessible by the public. Is this something that could be looked at?

**Comment by albogdano** [comment]
I'm afraid I can't give you much support for Docker. :neutral_face: My knowledge of it is quite limited. Try digging in the Docker docs for more information.
