### ISSUE TITLE
if deployed in a sub-directory, all image URLs break.

### ISSUE THREAD

**Issue by kaeverens** [Erudika/scoold#130]
I've set up Scoold to have a root at `/questions` on a server (using an NGinX rewrite). But when I view the system, it looks like this:

![image](https://user-images.githubusercontent.com/2878523/66031456-5c6bbe80-e4fb-11e9-828c-ec6f4e75729b.png)

the page's source code shows that all images are linked relative to the root of the server, not relative to the directory that Scoold is in.

**Comment by kaeverens** [comment]
damn - I should have R'd TFM.

![image](https://user-images.githubusercontent.com/2878523/66032169-cf296980-e4fc-11e9-9699-37496d7bcb16.png)

**Comment by albogdano** [comment]
@kaeverens I recently reviewed and checked all the code related to this and there were some issues which have been fixed in the latest version of Scoold. Do let me know if you encounter broken links etc., when using a different context path.
