### ISSUE TITLE
Switching off user email verification

### ISSUE THREAD

**Issue by timothyjmtan** [Erudika/scoold#132]
Hi!

I am currently running the following versions:
`para:  v1.34.2-SNAPSHOT` (self-compiled using OpenJDK11 from the para-jar package)
`sccold: v1.35.2` (the .jar file was downloaded from the website)

I had to compile `para` myself as my network is extremely restricted and prevents me from downloading the .jar file from the `para` website.

**Issue**
Objective: I would like to skip email authentication for newly registered users.

In the `application.conf` for `para`, I have added in `para.security.allow_unverified_emails = true`.
Additionally, for the `application.conf` for `scoold`, I am doing `para.password_auth_enabled = true
`.

What I've found is that after registering, I am still not able to immediately log in, even after turning the email authentication off in `para`.

After that, I tried using `para.password_auth_enabled = false`. However the entire login panel disappeared.

Could you point me in the right direction? Thanks!

**Comment by albogdano** [comment]
You have the two configuration files mixed up. https://github.com/Erudika/scoold#email-verification
1. By default, email verification is off when running Scoold in development mode. 
2. That configuration property belongs in the config file for Scoold.
3. The correct config property is `para.security.allow_unverified_emails = false`
4. If you turn of password authentication, you're left with no other option for login and the login panel  is blank. If you really want to turn off password authentication, you must configure at least one other authentication provider like Google, Facebook, OAuth 2.0, etc.
