### ISSUE TITLE
Problem of Twitter and Github OAuth login

### ISSUE THREAD

**Issue by mzch** [Erudika/scoold#135]
When enabling to Twitter and Github login, then an error occurred. Could you tell me how to fix this issue?

- Para : 1.34.1
- Scoold: 1.35.3

1. Github
  - Set callback URL to `https://useridea.com/github_auth`
  - Scoold reports 404 error, `https://usersidea.com/github_auth?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=scoold`

2. Twitter
  - Set callback URL to `https://useridea.com/twitter_auth`
  - Scoold tries to access to `http://127.0.0.1:8080/twitter_auth`, it's a port running local para instance.

`https://usersidea.com` is my scoold instance.

- application.conf
```
para.app_name = "Scoold"
# the port for Scoold
para.port = 8000
# change this to "production" later
para.env = "production"
# the URL where Scoold is hosted, or http://localhost:8000
para.host_url = "https://usersidea.com"
# the URL of Para - could also be "http://localhost:8080"
para.endpoint = "http://127.0.0.1:8080"
# access key for your Para app
para.access_key = "app:scoold"
# secret key for your Para app
para.secret_key = "xxxx=="
# needed for geolocation filtering of posts
para.gmaps_api_key = "xxxx"
# enable or disable email&password authentication
para.password_auth_enabled = true
# if false, commenting is allowed after 100+ reputation
para.new_users_can_comment = true
# the identifier of admin user - check Para user object
para.admins = "example@example.com"
# enables syntax highlighting in posts
para.code_highlighting_enabled = true
# If true, the default space will be accessible by everyone
para.is_default_space_public = true
# Mail settings
# system email address
para.support_email = "admin@usersidea.com"
para.mail.host = "192.168.207.21"
para.mail.port = 25
para.mail.tls = false
para.mail.ssl = false
# OAuth2
# Facebook
para.fb_app_id = "xxxx"
# Google
para.google_client_id = "xxxx.apps.googleusercontent.com"
# GitHub
para.gh_app_id = "xxxx"
para.gh_secret = "xxxx"
# Twitter
para.tw_app_id = "xxxx"
para.tw_secret = "xxxx"
```

**Comment by albogdano** [comment]
You need to whitelist the Para authentication endpoint because that is where the request is going after you click the button. So instead of `usersidea.com` use `yourparahost.com/github_auth`. Same for Twitter. The only exception to this rule is Facebook and Google - for these two providers you need to whitelist your Scoold URL `myscoold.com` and `myscoold.com/signin`

**Comment by mzch** [comment]
Is that so? OK. I changed para.endpoint and redirect URLs, then all things work!
Thank you, @albogdano !
