### ISSUE TITLE
Picture uploads with spaces in the file name.

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [Erudika/scoold#136]
I'm on Scoold PRO v1.35.3 when trying to upload a file on firefox (ubuntu 18.04) with spaces in its name the resulting markup is not working (i.e. the image does not expand).

**Comment by heprotecbuthealsoattac** [comment]
Just tested on chrome with the same effect. The image is uploaded correctly though.

**Comment by albogdano** [comment]
fixed
