### ISSUE TITLE
Welcome email a bit confusing.

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [Erudika/scoold#137]
Is it possible to change welcome email's text or disable it altogether without recompiling the source?

**Comment by albogdano** [comment]
You can only do it by editing the language file `lang_xx.properties` inside the JAR/WAR package.

**Comment by heprotecbuthealsoattac** [comment]
Yes but that requires me to open the jar which is a bit problematic (and hacky). Could we turn that issue into a feature request?

**Comment by heprotecbuthealsoattac** [comment]
Thank you!
