### ISSUE TITLE
Can I make wiki mode the default?

### ISSUE THREAD

**Issue by serenitus** [Erudika/scoold#139]
I'd like to make it the default that anyone can contribute to refining an answer. Is this possible?

**Comment by albogdano** [comment]
Add this to your Scoold configuration file:
```
# Enable/disable wiki style answers
para.wiki_answers_enabled = true
```

**Comment by asos-robbell** [comment]
Should this configuration be under **para**.xxx or **scoold**.xxx?

**Comment by albogdano** [comment]
@asos-robbell Use the `scoold.` prefix because the para. prefix was deprecated a while back.
