### ISSUE TITLE
[HELP] Fail to login via Twitter and GIthub

### ISSUE THREAD

**Issue by mzch** [Erudika/scoold#150]
I set `para.gh_app_id`, `para.gh_secret`, `para.tw_app_id` and `para.tw_secret` in both application.conf of para and scoold, then click 'Github' button or 'Twitter' button but scoold has not been shown Oauth screen.

homepage URL = `https://usercounsel.com`
callback URL  = `https://paraenv.com/github_auth`, `https://paraenv.com/twitter_auth`

Of course, scoold and para work normally.

Anyone can help me?

EDIT:
- Para URL: `https://paraenv.com`
- Scoold URL: `https://usercounsel.com`
- Scoold: 1.36.2
- Para: 1.34.3
- OpenJDK: 11.0.5
- OS: Debian 10.2

**Comment by albogdano** [comment]
Don't put those properties inside the Para configuration file. They are meant for Scoold only. 

Twitter seems to be working fine but GitHub is not configured properly. Make sure that the redirect URL is whitelisted for your GitHub OAuth app. Here's the error:

`error=redirect_uri_mismatch&error_description=`**The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.**`&error_uri=https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch&state=scoold`

**Comment by mzch** [comment]
Great! Thanks! :)
