### ISSUE TITLE
Syntax highlighting works incorrectly in dark mode

### ISSUE THREAD

**Issue by aostrowski** [Erudika/scoold#158]
When the dark theme is on, code posted in questions is incorrectly highlighted. Some keywords are invisible unless you select them.

This is how the code looks like when dark mode is off (this works correctly):

![image](https://user-images.githubusercontent.com/2119345/78704768-b024ed80-790c-11ea-85cd-4fd6af98f4f3.png)

and this is how it looks when dark mode is on (this is flawed):

![image](https://user-images.githubusercontent.com/2119345/78704704-8c61a780-790c-11ea-86ab-46d74bdcbbe2.png)

I used the following Markdown to create those snippets:
<pre>
```C++
#include <iostream>

// Some C++ code. 
int main() try {
	std::cout << "I wonder how the syntax will be highlighted\n";
} catch (std::exception&) {
}
```

```bash
if grep -q $USER script; then
	echo please make independent of username;
fi
```
</pre>

Reproduces both in Firefox and Chrome on Windows.

I used Scoold 1.38 deployed on Ubuntu 18.04 with a local instance of Para.

**Comment by albogdano** [comment]
Thanks @aostrowski! There may be other bugs in the CSS of the dark theme still. If you find anything else please report it down here or in another issue.
