### ISSUE TITLE
Tag not added to the filter automatically

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#162]
When clicking a tag under "Tags" the question filter is activated to show only questions with that particular tag. This is also visualized by the highlighted filter symbol.

But: when showing the filter menu by clicking the highlighted filter symbol, there's no tag added to "tags" section of the filter. So as a consequence, when clicking "apply" without any change, the filter gets cleared. 

Wouldn't it be more consistent, if the tag is automatically added to the filter after clicking it under "Tags"?

Seen in 1.39.2.

**Comment by albogdano** [comment]
I totally agree - this is a detail I've missed and will fix in the next release. Thanks again!
