### ISSUE TITLE
Question asked with activated "All spaces" is saved in "default space"

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#164]
Hi,
we are using

> Scoold Pro
Scoold version: 1.39.2
Production mode: true
Para app: app:scoold
Para version: 1.37.0

>is_default_space_public: false
auto_assign_spaces: test

"Test" is the only space we are using so all question go there.

When a regular user switches to "All spaces" and asks a question, this question will be saved to "default" space which is not accessible (despite to admin users).

There is no option for a regular users to configure the question to a space available to him (or as an alternative, Scoold could not allow asking questions when "All spaces" is active).

**Comment by albogdano** [comment]
I'm not sure how you managed to do that because you should have a space selection box underneath "tags". This select input should have "Test" selected by default.
![image](https://user-images.githubusercontent.com/346873/82221681-fec0a100-9928-11ea-8aff-4959fc57d11f.png)

**Comment by b-morgenthaler** [comment]
It happened on the production system and I could reproduce it on the test system. For the particular user, there was noch space selection box. Could it be a follow-up error because of the other issue with the "all spaces" bug? To reproduce this bug, we reproduced the other and had "all spaces" active while asking a new question for this issue

**Comment by albogdano** [comment]
Yes, this issue was definitely related to #163 and got resolved when I fixed the previous issue.
