### ISSUE TITLE
Maximum number of tags limited to 5?

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#166]
Hi,
we are using

> Scoold Pro
Scoold version: 1.39.2
Production mode: true
Para app: app:scoold
Para version: 1.37.0

I tried to add more than 5 tags to a question which isn't working. Is this a known/documented/configurable limitation? I didn't find any hint so far.

![Anmerkung 2020-05-19 142254](https://user-images.githubusercontent.com/52192619/82325927-51a76080-99dc-11ea-9b3d-f7ed7596d0ac.png)

Tried to figure out if this is overall count or char count specific, but the char count seems not to be problematic, it's the overall count.

**Comment by albogdano** [comment]
Yes, tags were always limited to 5. This limit is hardcoded and not yet configurable.

**Comment by b-morgenthaler** [comment]
Thanks for clarification. Didn’t find it documented anywhere… Would make a good Pro feature being able to add more than 5 tags :)

 

Regards.

 

Von: Alex Bogdanovski <notifications@github.com> 
Gesendet: Dienstag, 19. Mai 2020 15:11
An: Erudika/scoold <scoold@noreply.github.com>
Cc: Morgenthaler Björn <Bjoern.Morgenthaler@comlet.de>; Author <author@noreply.github.com>
Betreff: Re: [Erudika/scoold] Maximum number of tags limited to 5? (#166)

 

Yes, tags were always limited to 5. This limit is hardcoded and not yet configurable.

**Comment by albogdano** [comment]
Use the new configuration property for this:
```
# Tags per post limit, must be < 100
para.max_tags_per_post = 5
```

**Comment by b-morgenthaler** [comment]
Thank you very much! Will test with your next release of Scoold Pro.

**Comment by albogdano** [comment]
Yes, this will be in the next release which is coming out today.
