### ISSUE TITLE
LDAPS (ldap over ssl) configuration

### ISSUE THREAD

**Issue by technofab** [Erudika/scoold#168]
I've latest Scoold with also latest version of PARA, but I can't configure LDAPS authentication to connect to an active directory. Any advice?

Thanks in advance.

**Comment by albogdano** [comment]
I will need more information about you setup - type of LDAP server, is it accessible from Para, and so on...

**Comment by technofab** [comment]
Yes is accessible from Para and also Scoold. both are runned from the same server, with different binding tcp port,

I configure as the README only changing the ldap server port to 636 that is the LDAPS standard port,

For example
para.security.ldap.user_search_filter = "(&(objectClass=user)(sAMAccountName={1}))"
para.security.ldap.base_dn = "ou=dev,dc=scoold,dc=com"
para.security.ldap.server_url = "ldap://192.168.123.70:636"
para.security.ldap.active_directory_domain = "scoold.com"

**Comment by albogdano** [comment]
So it's an Active Directory server? You say "LDAPS" - did you try using "ldaps://192.168.123.70:636"?

**Comment by technofab** [comment]
Yes I'm using an active directory with ldaps auth, because soon LDAP will be disabled.

**Comment by albogdano** [comment]
Are you sure `para.security.ldap.active_directory_domain` is set correctly? That's the name of your AD domain controller

**Comment by technofab** [comment]
Yes, is setted correctly as mydomain.local

**Comment by albogdano** [comment]
To print out debug information about LDAP requests, start Para with 
`-Dlogging.level.org.springframework.ldap=DEBUG`
You might also check out this related issue: #67

**Comment by technofab** [comment]
I'll check then feedback, thanks for now.

**Comment by technofab** [comment]
I test and obtain this error:

2020-05-20 12:06:32 [34m[INFO ][0;39m Failed to authenticate 'albfab@zg.local' with LDAP server: simple bind failed: myserver.mydomain.com:636; nested exception is javax.naming.CommunicationException: simple bind failed: myserver.mydomain.com:636 [Root exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

I also import in chain as in this link with keytool full chain certificate (ca + issuing)
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

Any ideas?

**Comment by albogdano** [comment]
You have a problem with the LDAP server certificate apparently. Either you're using a self-signed certificate or an invalid one.

**Comment by technofab** [comment]
No, I'm using an internal CA and all other server use the same CA and CA Certificate. The CA is che Active Directory Certification Autority where I can obtain single certificates. In this case I retrieve a full chain certificate. The domain CA is also loaded system wide in the server. The server is a Windows 2019 Server.

**Comment by albogdano** [comment]
Try running Para with these system properties configured:
```
-Djavax.net.ssl.keyStorePassword=passwordForKeystore \
-Djavax.net.ssl.keyStore=pathToKeystore.ks \
-Djavax.net.ssl.trustStore=pathToTruststore.ts \
-Djavax.net.ssl.trustStorePassword=passwordForTrustStore
```

**Comment by albogdano** [comment]
These more info here: https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-error-779355358.html

> Use SSL Poke to verify connectivity
> Try the Java class SSLPoke to see if your truststore contains the right certificates. This will let you connect to a SSL service, send a byte of input, and watch the output.

[Code for SSL Poke](https://confluence.atlassian.com/download/attachments/117455/SSLPoke.java)

**Comment by technofab** [comment]
I'vent this parameters.. but we have imported our full chain cer with the keytool:

keytool -import -alias -ca -file C:\mycerts\chain.cer -keystore "C:\Program Files\Java\jdk1.8.0_202\jre\lib\security\cacerts"

**Comment by albogdano** [comment]
I'm not sure if that's enough though. You should tell Java where to look for the keystore.

**Comment by technofab** [comment]
The standard keyostore pat fo CA in hava is the cacerts file.

I try the sslpoke utiliy and obtain same error:

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by albogdano** [comment]
I can't really help you much with that error as it is outside the scope of Para and Scoold. It could be that the certificate is not imported properly.

**Comment by technofab** [comment]
Also in the atlassian link I use:
C:\kit>java -Djavax.net.ssl.trustStore="C:\Program Files\Java\jdk1.8.0_202\jre\lib\security\cacerts" SSLPoke myldapserver 636 and respond conncetions successful. I can add that parameters?

**Comment by albogdano** [comment]
OK, good! You should start Para with that system property and the LDAP connection should work as well.

**Comment by technofab** [comment]
Thanks for your help. I restart all with these parameter and it works.

In brief, to work with AD and LDAPS auth all system need to isssue a Full Chain CA Certificate from AD CA, import that in the default cacerts of the running Java JVM and add 2 more paramters in the startup:
-Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true 
-Djavax.net.ssl.trustStore="C:\Program Files\Java\jdk1.8.0_202\jre\lib\security\cacerts"

The second must be reflect the real path of cacerts files.

**Comment by albogdano** [comment]
Well done and thanks for the explanation! Closing this issue as 'resolved'.
