### ISSUE TITLE
Admin's default space shows all questions from all spaces

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#170]
Hi,

we are using 

>Scoold Pro
Scoold version: 1.39.3
Production mode: true
Para app: app:scoold
Para version: 1.37.0
Para endpoint: http://localhost:8080

with
>is_default_space_public: false

With this configuration, only admin accounts see "default space". When activated (see attached screenshot), the default space seems to act more than regular user's "all spaces" because the questions from all spaces ("default", "test", and "bm_only") are shown. And what is even more unexpected is that this particular admin account has only "test" space configured.

![Anmerkung 2020-05-26 084545](https://user-images.githubusercontent.com/52192619/82868764-7c8a3b00-9f2d-11ea-98ad-d9c2eda59527.png)

Is this intentional?

Best regards,
Björn

**Comment by albogdano** [comment]
I'll see what I can do to make this less confusing but basically for admins it doesn't matter what spaces you are part of. Selecting a space from the menu would simply filter the questions for that space. 
The default space is exactly like "All spaces" but you actually see all spaces and questions (when admin).

**Comment by b-morgenthaler** [comment]
Ok, I understand. That means that the „bulk edit spaces” functionality has no effect for admin accounts, correct? Maybe that’s a place for clearing things up: since admin accounts see all spaces per definition this could be reflected by UI by not being able to edit spaces for admins?

 

The context of my question was more for security reasons: I’m thinking about using spaces for different customer projects (asking project/customer specific questions). But with that I have to be sure that users not configured to a space, do not see questions of that space by any chance.

**Comment by albogdano** [comment]
I'll probably make it impossible for admins to leave a space and also they will be able to select any space from the dropdown menu.
