### ISSUE TITLE
Beginner Query: accessing the REST API

### ISSUE THREAD

**Issue by genloz** [Erudika/scoold#173]
Hi!

Just wondering if there's a configuration item I'm missing for API access somewhere?

In the application.conf I added:
```
para.api_enabled = true
para.app_secret_key = "XXXXXX"
```
And the 'Administration' page displays the API Keys header and 'generate' button. But when I click 'generate' nothing happens. 
The console shows the following error: 
`http://mywebsite.com/admin/generate-api-key 403 (Forbidden)`

The api page returns: 
`{"healthy":true,"message":"AppTest API, see docs at http://mywebsite.com/apidocs","pro":false}`

Advice appreciated! 

Thank you!

**Comment by albogdano** [comment]
How long is the `app_secret_key`? Must be >= 32 characters.

**Comment by genloz** [comment]
That worked, thank you!
