### ISSUE TITLE
Photos do not render

### ISSUE THREAD

**Issue by thomdask** [Erudika/scoold#178]
Hi, 

when I upload a photo on a question or an answer, the photo is not being rendered.

See attached screenshots.

<img width="844" alt="question edit" src="https://user-images.githubusercontent.com/21304764/85866360-f1bc8a80-b7cf-11ea-97cf-640f0d665fe4.png">
<img width="585" alt="view" src="https://user-images.githubusercontent.com/21304764/85866370-f41ee480-b7cf-11ea-8b9d-c04f7cf80f9c.png">

Is this a bug or am I doing something wrong?

Thanks a lot in advance
Thomas

**Comment by albogdano** [comment]
Can't say why this happens exactly. Can you open the image link in your
browser? Also check the browser dev console for errors.

**Comment by thomdask** [comment]
It was my fault and the reason for the error was well described https://github.com/Erudika/scoold/blob/master/README.md#content-security-policy-header
