### ISSUE TITLE
docker compose installation fails

### ISSUE THREAD

**Issue by csbrown** [Erudika/scoold#179]
```
ERROR: Named volume "{'type': 'volume', 'source': 'paraLib', 'target': '/para/lib'}" is used in service "para" but no declaration was found in the volumes section.
```
I have followed the instructions to deploy via docker compose exactly.  Adding the line:

```
  paraLib:
```

to the end of `docker-compose.yml` solved the problem, but I'm new here so I'm not sure if this is a documentation problem, or a problem in the yml.

**Comment by albogdano** [comment]
It was a problem with the docker-compose.yml file. Thanks!
