### ISSUE TITLE
Uploading a file on a new question causes the text content to be deleted.

### ISSUE THREAD

**Issue by jorgeag68** [Erudika/scoold#182]
When writing a new question and if uploading a file at the same time, the content of what I have written in the editor field is lost. 

Problem with the PRO version released yesterday.

scoold-pro-1.39.5.jar

This is a blocker for us.

**Comment by jorgeag68** [comment]
I see the issue is closed.  When can we expect a new build to be available ?
Thank you.

**Comment by jorgeag68** [comment]
hello. I've downloaded and  run latest version... And still all test on the description gets replaced by the attachment link once we add a file. Example

:paperclip: [TCP_Flow_CPE_unit.pdf](https://faq.axiros.com/upload/files/1594673015860_TCP_Flow_CPE_unit.pdf)

![image](https://user-images.githubusercontent.com/23095798/87351941-295a5f00-c552-11ea-805a-10652be762a8.png)

**Comment by albogdano** [comment]
Please clear your browser cache and refresh the page.

**Comment by jorgeag68** [comment]
Thanks. I confirm it works.
