### ISSUE TITLE
Allow to configure which file types are supported for upload.

### ISSUE THREAD

**Issue by jorgeag68** [Erudika/scoold#183]
Add an option to allow to configure which file types do we want to support by adding a configurable option on the application.conf.

There are some file types that we would like to include as supported to upload on our setup, like:

.py , .yml, .json

Thank you.

**Comment by albogdano** [comment]
Added option `para.allowed_upload_formats = "py,yml,json"`. You wouldn't have to set it because I've already included these file types in the whitelist. **This option is only valid in Scoold Pro**.
