### ISSUE TITLE
Dark mode as global setting

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#185]
Hi,

we are using 

> Scoold Pro
Scoold version: 1.39.6
Production mode: true
Para app: app:scoold
Para version: 1.37.1

Each user (also non-admins) can enable/disable dark mode. This setting seems to be a global setting because when user A enables dark mode and logs out, logging in with user B an the same desktop with the same browser session, dark mode is also enabled for user B.

If it's intended to be a global setting, I vote that only admin user shall change it.

**Comment by albogdano** [comment]
Thanks for bringing this up! Dark mode can also be set globally as a theme now from the Administration page. Dark mode can be cleared by removing the `dark-mode: 1` cookie.
