### ISSUE TITLE
Deployment with docker-compose: authentication with LPAP does not work

### ISSUE THREAD

**Issue by hth2** [Erudika/scoold#186]
I have deployed scoold with docker-compose and it seems up and running: I can sign up, got verification link via email and login.

Now I am trying to get LDAP authentication working but got stuck.

(1) I have tested that connection to ldap works with ldapsearch:
```
ldapsearch -H ldap://192.168.30.10:7389 \
-x -D "uid=scoold,cn=users,dc=xyz,dc=com" \
-b "dc=xyz,dc=com" \
-w PASSWORD \
'(uid=abc)'

```

(2) my LDAP config in scoold-application.conf is:

```
para.security.ldap.server_url = "ldap://192.168.30.10:7389/"
para.security.ldap.base_dn = "dc=xyz,dc=com"
para.security.ldap.bind_dn = "uid=scoold,cn=users,dc=xyz,dc=com"
para.security.ldap.bind_pass = "PASSWORD"
para.security.ldap.user_search_base = "cn=users,dc=xyz,dc=com"
para.security.ldap.user_search_filter = "(uid={0})"
#para.security.ldap.user_dn_pattern = "uid={0}"
para.security.ldap.password_attribute = "userPassword"

```

(3) I enabled debugging by having this line in scoold.env:
`JAVA_OPTS=-Dconfig.file=/scoold/application.conf -Dlogging.level.com.erudika.para.client=DEBUG`

(4) when docker-compose started, the following info was in log:

```
security.ldap.bind_dn=uid=scoold,cn=users,dc=xyz,dc=com
security.ldap.admins_group_node=
security.ldap.password_attribute=userPassword
security.ldap.server_url=ldap://192.168.30.10:7389
security.ldap.bind_pass=PASSWORD
security.ldap.base_dn=dc=xyz,dc=com
security.ldap.active_directory_domain=
security.ldap.user_dn_pattern=uid={0}
security.ldap.mods_group_node=
security.ldap.user_search_filter=(uid={0})
security.ldap.user_search_base=cn=users,dc=xyz,dc=com
security.ldap.username_as_name=false

```

(5) when abc user tried to login, I got in log:
```
scoold_1  | 2020-07-28 22:48:30 [DEBUG] POST /jwt_auth, entity: Entity{entity={provider=ldap, appid=app:scoold, token=abc:ABC_PASS}, variant=Variant[mediaType=application/json, language=null, encoding=null], annotations=[]}
para_1    | 2020-07-28 22:48:30 [WARN ] Failed to authenticate user with LDAP server: [LDAP: error code 32 - No Such Object]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - No Such Object]; remaining name 'cn=users,dc=xyz,dc=com'
para_1    | 2020-07-28 22:48:30 [INFO ] Failed to authenticate 'abc' with LDAP server: LDAP user not found.
scoold_1  | 2020-07-28 22:48:31 [ERROR] 400 - Failed to authenticate user with 'ldap'. Check if user is active.

```

I cannot think of any other reason than  the user with DN uid=scoold,cn=users,dc=xyz,dc=com cannot connect to the LDAP server. Therefore I have checked many many times the login credentials and I am sure it's correct. 

Any hint what else I could try to troubleshoot this problem?

**Comment by albogdano** [comment]
Try removing bind_dn and bind_pass properties from the configuration.

To print out debug information about LDAP requests, start Para with:

 -Dlogging.level.org.springframework.ldap=DEBUG.

**Comment by hth2** [comment]
thank you for your suggestion.

I removed bind_dn and bind_pass from scoold-application.conf, and added to para.env:
`JAVA_OPTS=-Dconfig.file=/para/application.conf -Dloader.path=lib -Dlogging.level.org.springframework.ldap=DEBUG`

after docker-compose stop-start, login, I get a slightly different output from logs:

```
para_1    | 2020-07-29 11:37:55 [DEBUG] Using LDAP pooling.
para_1    | 2020-07-29 11:37:55 [DEBUG] Trying provider Urls: ldap://192.168.30.10:7389/dc=xyz,dc=com
para_1    | 2020-07-29 11:37:55 [DEBUG] Using LDAP pooling.
para_1    | 2020-07-29 11:37:55 [DEBUG] Trying provider Urls: ldap://192.168.30.10:7389/dc=xyz,dc=com
para_1    | 2020-07-29 11:37:55 [DEBUG] Got Ldap context on server 'ldap://192.168.30.10:7389/dc=xyz,dc=com'
para_1    | 2020-07-29 11:37:55 [WARN ] Failed to authenticate user with LDAP server: [LDAP: error code 32 - No Such Object]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - No Such Object]; remaining name 'cn=users,dc=xyz,dc=com'
para_1    | 2020-07-29 11:37:55 [INFO ] Failed to authenticate 'abc' with LDAP server: LDAP user not found.
scoold_1  | 2020-07-29 11:37:55 [ERROR] 400 - Failed to authenticate user with 'ldap'. Check if user is active.

```

it seems that `-Dlogging.level.org.springframework.ldap=DEBUG` has no efffect?

**Comment by albogdano** [comment]
The value for `JAVA_OPTS` should be quoted, like `JAVA_OPTS="-Dconfig.file=/para/application.conf -Dloader.path=lib -Dlogging.level.org.springframework.ldap=DEBUG"`. What type of LDAP server is this?

**Comment by hth2** [comment]
The LDAP server in question is a OpenLDAP server:
`2.4.45+dfsg-1~bpo9+1A~4.4.0.202004291153`

```
# slapd -V
@(#) $OpenLDAP: slapd  (Apr 29 2020 09:53:20) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>

```
I tried to remove the  quote, but then got this error in log:

`para_1    | Error: Could not find or load main class "-Dconfig.file=.para.application.conf`

This looks suspicious, but I don't know how to process further. When I removed the quote the error went away.

**Comment by albogdano** [comment]
Ok, so maybe if the JAVA_OPTS is inside a `para.env` file it should not be quoted but I'm not 100% sure.
How about this config:
```ini
para.security.ldap.server_url = "ldap://192.168.30.10:7389/"
para.security.ldap.base_dn = "dc=xyz,dc=com"
para.security.ldap.user_search_base = "dc=xyz,dc=com"
para.security.ldap.user_search_filter = "uid={0},cn=users"
para.security.ldap.user_dn_pattern = "uid={0}"
```

**Comment by hth2** [comment]
I tried the suggested config, unfortunately it made no difference.

I also tried the following:
* use JAVA_TOOL_OPTIONS instead of JAVA_OPTS as suggested  [here](https://stackoverflow.com/questions/53785577/passing-java-opts-to-spring-boot-application-through-docker-compose)
* try both with and without quote

With quote I get a lot of errors in log, and scoold doesn't seem up, so probably without quote is correct

JAVA_TOOL_OPTIONS seems to be picked up by both para & scoold:

```
para_1    | Picked up JAVA_TOOL_OPTIONS: -Dconfig.file=/para/application.conf -Dloader.path=lib -Dlogging.level.org.springframework.ldap=DEBUG
scoold_1  | Picked up JAVA_TOOL_OPTIONS: -Dconfig.file=/scoold/application.conf -Dlogging.level.com.erudika.para.client=DEBUG
```

however the login still fails with same messages as before.

**Comment by hth2** [comment]
I finally got it working after countless trial-and-errors. Here is a summary for reference:

- install method: docker-compose, erudikaltd/scoold:1.39.3, erudikaltd/para:v1.37.0
- ldap server: openldap-2.4.45 on UCS (which is based on debian)
- users have DNs as uid=abc,cn=users,dc=xyz,dc=com
- Java options in scoold.env:
`JAVA_TOOL_OPTIONS=-Dconfig.file=/scoold/application.conf -Dlogging.level.com.erudika.para.client=DEBUG`
- Java options in para.env (thanks to this [post](https://stackoverflow.com/questions/51558193/error-authenticating-with-ldap-in-spring-boot-reason-ldap-error-code-50-ins) )
`JAVA_TOOL_OPTIONS=-Dconfig.file=/para/application.conf -Dloader.path=lib -Dlogging.level.org.springframework.ldap=DEBUG -Dlogging.level.org.springframework.security=DEBUG
`
- enable debugging on ldap server by having in slapd.conf (which helped me to see the requests from scoold):
`loglevel any`

- final ldap config:
```
para.security.ldap.server_url = "ldap://192.168.30.10:7389"
para.security.ldap.base_dn = "cn=users,dc=xyz,dc=com"
para.security.ldap.user_search_filter = "uid={0}"
```
