### ISSUE TITLE
More than a few comments are not visible when numeric_pagination_enabled is True

### ISSUE THREAD

**Issue by thomdask** [Erudika/scoold#188]
I have one question posted with one answer. The URL of the question is `/question/1201897295558217728/XXX`
<img width="934" alt="comments" src="https://user-images.githubusercontent.com/21304764/89502240-5b678580-d7cd-11ea-9aeb-4248de2de6f9.png">
The answer has 5 comments. When a 6th one is added, it appears properly after add but then when the page is reloaded it disappears. When I click to go to the next page of comments I get an error like seen below.

The URL it redirects me (and the one that shows the "Nothing found." error is `/comment?getcomments=true&parentid=1201899946651947008&page=2`)

<img width="549" alt="page2" src="https://user-images.githubusercontent.com/21304764/89502263-64585700-d7cd-11ea-89c6-f46426d288a4.png">

**Comment by albogdano** [comment]
This is not normal behavior. You probably have some sort of JS error in your browser console. I cannot reproduce this.

**Comment by albogdano** [comment]
I noticed that you have enabled numeric pagination. This pagination mode is relatively new and still has some issues. I will fix this later today.

**Comment by thomdask** [comment]
There are no JS errors in the console. Tried with different browsers, no errors and same behavior.
Do you suggest that if I set the para.numeric_pagination_enabled to false the issue would go away?

**Comment by albogdano** [comment]
Yes, the issue only affects numeric pagination.

**Comment by thomdask** [comment]
> Yes, the issue only affects numeric pagination.

Confirmed.
