### ISSUE TITLE
Add support for links and code on comments

### ISSUE THREAD

**Issue by thomdask** [Erudika/scoold#189]
I would like to make a feature request to be able to highlight code and URL links in the comments. Not necessarily a full blown rich editor like there is for answers but it would be nice if URLs are clickable and code can render as such when I include it in ``

**Comment by thomdask** [comment]
I just realized that they are supported but hidden to the user. Maybe add a little help icon to make it obvious?

**Comment by albogdano** [comment]
Yes, markdown is supported inside comments. I will also add a small text label under the comment text area.
