### ISSUE TITLE
Scoold signup fails

### ISSUE THREAD

**Issue by thomashrabe** [Erudika/scoold#190]
I am setting up my own scoold server with para and I am having difficulty to sign up.
We have no SMTP server configured, so even without a SMTP specification the UI tries to validate 
a new user through email. Deadend.

I tried appending `para.security.allow_unverified_emails = true` and then sign up does not work at all. The UI is blank.

In conclusion, the Scoold interface is not useable. It looks very promising.

Can you please share a configuration how to properly disable email verification?

**Comment by albogdano** [comment]
Do you set `para.password_auth_enabled = true`? I'm not sure how the UI is blank on `/signin/register` because I cannot reproduce this.

**Comment by thomashrabe** [comment]
You can close this. I found the issue in my config. I had 
```
para.password_auth_enabled = false
```

and that was giving blank login screens.

![Screen Shot 2020-08-10 at 11 05 35 AM](https://user-images.githubusercontent.com/3632672/89817072-6dfafb00-dafc-11ea-911f-e1bbe5218d6f.png)
