### ISSUE TITLE
How to test sending emails inside container(s)?

### ISSUE THREAD

**Issue by hth2** [Erudika/scoold#191]
How can I test sending emails from the scoold container? From the docker host I can send mail. However when I sign up, scoold said email has been successfully sent, but  the email from scoold is not delivered.

The relevant part in scoold-application.conf looks as follows:

```
para.mail.host = 1.2.3.4
para.mail.port = 25
para.mail.tls = false
para.mail.ssl = false
```

This is an stmp relay which accepts emails from trusted IPs, without authentication.

**Comment by albogdano** [comment]
First enable SMTP logging with `para.mail.debug = true` then just try resetting your password and check for a reset password email.
