### ISSUE TITLE
How to upgrade or downgrade docker image?

### ISSUE THREAD

**Issue by hth2** [Erudika/scoold#192]
I have installed an instance of scoold from docker image with the tag latest a few days ago. Now I am trying to setup another site, with identical settings except the url. It works mostly except email sending and ldap auth over LDAPS. 

I thought it could be that I am using different docker images, so I did check the versions. The first site is running on the container with

`"Image": "sha256:597ed93b58082c57b6f55618d3edf891f14a88aa2a7f8f17608fbb19cad4a832"
`

(output from `docker inspect ID`)

But it seems this image is no longer available from docker hub. Therefore I am thinking of:

(1) downgrading the image of scoold to 1.39.4, or
(2) upgrade the image of scoold to `latest`

What is the recommended path in this case?

**Comment by albogdano** [comment]
I would not recommend using the latest tag in docker as it may contain some unstable changes. You can just restart the container with the newest tag right? You can also do a `docker pull` to get the latest `:latest` image and restart the container but I would stick to tagged images.
