### ISSUE TITLE
Add support for notifications on comments

### ISSUE THREAD

**Issue by thomdask** [Erudika/scoold#201]
When there is a reply to a comment of a user, there can not be a notification according to the existing settings.

Would it be possible to add another setting to enable notifications for all activity on a question that a user has been involved with (comments and/or answers)?

Thanks in advance

**Comment by albogdano** [comment]
You mean when someone adds a comment under an answer to your question? Or do you mean when person A comments on a post by person B and then person C adds another comment, you want person A to receive a notification that person C added a comment? But that's already implemented with @ mentions.

**Comment by thomdask** [comment]
Person A posts a question. Person B comments. Person A adds a comment. Person B should get the notification about Person’s A comment. You are right that mentions work but many times users reply to a comment without a mention..

**Comment by albogdano** [comment]
Done. There's no need to modify the configuration or anything here. Just enabling comment notifications will get you notified as a participant in a comment thread.
