### ISSUE TITLE
LDAP configuration failed

### ISSUE THREAD

**Issue by pbabilas** [Erudika/scoold#202]
Hi, I've got scoold configured and running but can't login via LDAP.
I configured my ldap as in any other apps and it's not working. I'm getting msg:

> 2020-10-01 07:18:28 [ERROR] 400 - User belongs to an app that does not exist.

No other information, I dunno if my configuration is wrong, or its ap problem? No docs are provided. No logs are provided, any idea how to debug it or how to resolve this issue?

**Comment by albogdano** [comment]
- Did you go through all the deployment steps [listed here](https://github.com/Erudika/scoold#quick-start-with-a-self-hosted-para-backend-harder)? 
- Did you initialize Para? 
- Did you create a dedicated child app in Para for your Scoold instance?

**Comment by pbabilas** [comment]
Hi, worked it out again and now works. Seams that access_key was missing. Now its working. But error log was short so I can not known what was wrong. Not its ok.
