### ISSUE TITLE
profile pics for SAML

### ISSUE THREAD

**Issue by mirt001** [Erudika/scoold#213]
currently profile pictures do not seem to be filled from SAML authentications, but this would be a nice feature.
Ideally, when a user authenticates using SAML, their profile picture with the IdP should be used as profile picture in Scoold.
This is a feature request.

**Comment by albogdano** [comment]
This is already suppored in the [`SAMLAuthFilter`](https://github.com/Erudika/para/blob/d2c6d9a95ecd1a36ebf3920912add5b6228a6387/para-server/src/main/java/com/erudika/para/security/filters/SAMLAuthFilter.java#L238). You need to set `para.security.saml.attributes.picture` to be the name of attribute where the avatar is stored in SAML.
