### ISSUE TITLE
Reputation can be changed by refresh and upvote/downvote

### ISSUE THREAD

**Issue by almondflower** [Erudika/scoold#221]
Hey, on those versions :
  image: erudikaltd/scoold:1.41.2
  image: erudikaltd/para:v1.38.4

By refresh on a question/response you can change multiple times the reputation of the answerer.

Each refresh permit the same person to upvote/downvote multiple times on an answer.

Can you fix that ?

Thansk in advance.

**Comment by albogdano** [comment]
This is not normal behavior and I can't reproduce it. Probably your instance is not configured properly.
