### ISSUE TITLE
Replies posted to channel by slack integration show incorrect question author

### ISSUE THREAD

**Issue by webandtech** [Erudika/scoold#223]
Posting a reply to a question answered by someone else shows up in slack as if the question was asked by the answerer.

Example:

Jane Doe asks question: What is Scoold?
Mike Smith answers question What is Scoold?

Shows in Slack as:

```
@Mike Smith replied to What is Scoold?, created by @Mike Smith 2h ago.
```

The created by should show Jane Doe instead of Mike Smith

**Comment by albogdano** [comment]
Fixed. Thanks for reporting this Aaron!
