### ISSUE TITLE
OAuth2 login doesn't seem to work

### ISSUE THREAD

**Issue by Loreno10** [Erudika/scoold#227]
I have Scoold running locally. I wanted to add OAuth2 login (using Azure Active Directory as IdP).
Here's the config that I'm using:

```env
para.env = "production"
para.endpoint = "http://para:8080"
para.access_key = "app:para"
para.secret_key = "{para-key}"

para.password_auth_enabled = false

# minimal setup
para.oa2_app_id = "{my client ID}"
para.oa2_secret = "{my secret}"
para.security.oauth.authz_url = "https://login.microsoftonline.com/{my tenant ID}/oauth2/v2.0/authorize"
para.security.oauth.token_url = "https://login.microsoftonline.com/{my tenant ID}/oauth2/v2.0/token"
para.security.oauth.profile_url = "https://graph.microsoft.com/oidc/userinfo"
para.security.oauth.scope = "openid email profile"

# extra options
para.security.oauth.parameters.id = "sub"
para.security.oauth.parameters.email = "email"
para.security.oauth.parameters.name = "name"

# Sets the string on the login button
para.security.oauth.provider = "Login using AAD"

# Enable/disable access token delegation
para.security.oauth.token_delegation_enabled = false
```

When I run Scoold, I see this:

![image](https://user-images.githubusercontent.com/10273406/113008081-04a52680-9177-11eb-8838-c2d86beaa7fd.png)

As I'd expect, only AAD login is enabled. However, clicking the button has no reaction.
The HTML looks like this:

![image](https://user-images.githubusercontent.com/10273406/113008228-256d7c00-9177-11eb-877f-b185024fba96.png)

The button points to `#`, which basically does nothing.
What am I doing wrong?

**Comment by Loreno10** [comment]
That worked! It looks like a bug :)

**Comment by albogdano** [comment]
Yeah, I'm planning to get rid of the JS code for all signin buttons and use simple href links instead.

**Comment by Loreno10** [comment]
Ok. Is there some workaround for now? I think the users will not easily figure out that you need to refresh every time to have login button working.

**Comment by Loreno10** [comment]
@albogdano Although the button does work, I have another struggle. 
My authorization finishes with:
![image](https://user-images.githubusercontent.com/10273406/113012889-78493280-917b-11eb-8328-2afc6cdfe26b.png)

I noticed the following in my browser's DevTools:

After I log in with my IdP, I am redirected to: `http://localhost:8080/oauth2_auth?code=0.AQIA4Oku....` (code truncated)
This results in 302, which redirects me to `http://localhost:8000/signin/success?jwt=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjg3NzY1ODg4OTU0NTM1OTM2IiwibmJmIjoxNjE3MTE3MDYzLCJpZHAiOiJvYXV0aDIiLCJhcHBpZCI6ImFwcDpwYXJhIiwicmVmcmVzaCI6MTYxNzEyMDY2MzIxMCwiZXhwIjoxNjE3NzIxODYzLCJpYXQiOjE2MTcxMTcwNjN9.h80O67lvXFwHThZiCw6u1x7Kpg9Tu4PnnbME2-T-_1Y`.

The JWT seems to be attached by Para. After decoding it, I see this:

```json
{
  "alg": "HS256"
}.{
  "sub": "1287765888954535936",
  "nbf": 1617117063,
  "idp": "oauth2",
  "appid": "app:para",
  "refresh": 1617120663210,
  "exp": 1617721863,
  "iat": 1617117063
}.[Signature]
```

Unfortunately, this request is another redirect, this time to `http://localhost:8000/signin?code=3&error=true`.
Which results is an error that I posted a screenshot of above.

I wonder, why Para creates this JWT instead of requesting a JWT (I guess OpenID IdToken) from my IdP?

**Comment by albogdano** [comment]
Users won't have to refresh the login page because that bug rarely happens, usually when you have the cached JS file and change configuration. 
Using the root app `app:para` for Scoold is not recommended. You should create a separate app `app:scoold` or similar. 
Yes, Para creates that JWT. The problem comes from the fact that `para-auth` is a cookie used by Para itself for a different purpose and Scoold usually works with the `scoold-auth` cookie.

> Btw, would you like me to add the Azure Active Directory setup procedure to README.md? I see that you have instructions for Okta, AAD setup is a bit different.
Sure, go ahead! That would be helpful to others as well.

**Comment by Loreno10** [comment]
Ok, so I generated a new app, as you suggested. Unfortunately, I end up with the same result - there's an error.
Now, the JWT that I see in DevTools is:

```json
{
  "alg": "HS256"
}.{
  "sub": "1287798967307866112",
  "nbf": 1617119785,
  "idp": "oauth2",
  "appid": "app:scoold",
  "refresh": 1617123385230,
  "exp": 1617724585,
  "iat": 1617119785
}.[Signature]
```

So, the `appid` is now different.
The console prints the same error though:

![image](https://user-images.githubusercontent.com/10273406/113019228-a598df00-9181-11eb-872a-aaed9e312c2b.png)

**Comment by Loreno10** [comment]
I figured that out - I added `para.app_name = "Scoold"` to my Scoold config. It is missing in the Docker Compose example. I'll add it in another PR.
