### ISSUE TITLE
Need a scoold-specific user admin area in admin

### ISSUE THREAD

**Issue by bsommardahl** [Erudika/scoold#23]
I know power-users and devs can manage users in Para, but some things are very difficult for normal users. For instance, granting admin privileges to someone is too complicated. We need a way in scoold to just click a button and all our dreams come true. :)

**Comment by albogdano** [comment]
I'm on it!

**Comment by albogdano** [comment]
Use the new configuration option:
```
para.admins = "joe@example.com,fb:1023405345366,gh:1234124"
```
