### ISSUE TITLE
Changing logo instructions are not clear

### ISSUE THREAD

**Issue by marcinjahn** [Erudika/scoold#232]
I cloned the repo, and changed the /src/main/resources/logo.svg file to something custom.
However, after building a Docker image, and running it, I'm still getting the default Scoold logo.
I also tried using `para.logo_url = "/logo.svg"` .conf file, but this results in no logo being displayed at all.

How should I change the logo?

**Comment by albogdano** [comment]
The idea is to set the logo to a valid URL `para.logo_url = "https://static.scoold.com/logo.svg"` without having to modify the internal files of the container/JAR. I updated the readme.

**Comment by Loreno10** [comment]
What about the case if one wants to have the file locally on the server? Is that possible?

**Comment by albogdano** [comment]
That's a feature in Scoold Pro - you can upload an image for the logo. But in your case, changing `"/logo.svg"` to `"/images/logo.svg"` should do the trick.

**Comment by Loreno10** [comment]
Yeah, right. Sorry, forgot that
