### ISSUE TITLE
Email notifications are not clear

### ISSUE THREAD

**Issue by Loreno10** [Erudika/scoold#234]
[SMTP section](https://github.com/Erudika/scoold#smtp-configuration) and the [Welcome email section](https://github.com/Erudika/scoold#welcome-email-customization) mention possibilities of sending various emails to users. It's not clear what kind of emails are possible.

I understand that *Welcome mail* is sent when the user registers (or signs in with an external IdP for the first time). I see that we can modify the mail's body. However, can we also disable that kind of mail completely?

Then, the notifications mentioned in *SMTP* section aren't explained - what kind of notifications are these? May they be configured like Welcome mails? May they be disabled?

**Comment by albogdano** [comment]
The default email messages cannot be disabled, like the welcome message and password reset messages. The other mail notifications are controlled by each user separately. 
Only the welcome email can be customized for now.
Emails are sent when:
- user registers with email (email verification)
- user logs in for the first time (welcome)
- user wants to reset their password
- user wants to get notifications for new replies, comments or new posts
- user wants to get notifications for new questions tagged with a favorite tag
