### ISSUE TITLE
An illegal reflective access operation has occurred error

### ISSUE THREAD

**Issue by Loreno10** [Erudika/scoold#236]
When running Scoold locally, I see occasionally this error:

```sh
scoold_1         | WARNING: An illegal reflective access operation has occurred
scoold_1         | WARNING: Illegal reflective access by org.glassfish.jersey.client.internal.HttpUrlConnector$3 (jar:file:/scoold/scoold.jar!/BOOT-INF/lib/jersey-client-2.32.jar!/) to field java.net.HttpURLConnection.method
scoold_1         | WARNING: Please consider reporting this to the maintainers of org.glassfish.jersey.client.internal.HttpUrlConnector$3
scoold_1         | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
scoold_1         | WARNING: All illegal access operations will be denied in a future release
```

WHat is the cause of it? Is it something to worry about?

**Comment by albogdano** [comment]
This will be fixed in the near future. The Jersey REST client library is responsible for the warning so I can't fix it. Just don't use Java 16 for now. :sweat_smile:

**Comment by albogdano** [comment]
Related issue: https://github.com/payara/Payara/issues/5097

**Comment by Loreno10** [comment]
Ok, so this warning does not have any actual negative side effects? I mean, can I just ignore it and live in peace? :)

**Comment by albogdano** [comment]
Yes, ignore it for now. But don't ignore it if you plan to use Java 16.

**Comment by Loreno10** [comment]
Got it. Since I'm planning to rely on Docker images provided by Erudika, I guess I don't have to worry at all.

**Comment by albogdano** [comment]
Yes, indeed. I am aware of this and by the time we release Java 16+ compatible docker images these warnings will be fixed.
