### ISSUE TITLE
Option to disable "Dark Mode" option

### ISSUE THREAD

**Issue by Loreno10** [Erudika/scoold#237]
I think there should be a way to disallow users from switching to "Dark Mode"
![image](https://user-images.githubusercontent.com/10273406/113273477-fa9d3800-92dc-11eb-9966-1798082215ff.png)

It's important in cases where Scoold is set up with some custom CSS, which might not be very "Dark Mode friendly".
Or, more generally, possibly some sites would have to follow some strict styling rules, where Dark Mode is not part of allowed branding.

**Comment by albogdano** [comment]
Added `para.dark_mode_enabled = true`

**Comment by Loreno10** [comment]
Cool!
