### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#238]
Observered behavior: When searching for a string like "qt" which is neither a tag nor mentioned in any q/a, search will show up two random user as result. Those user do not have any substring "qt" within their name or similar.

From Gitter: Alex Bogdanovski @albogdano Apr. 07 13:14
@b-morgenthaler Ok, search may need some more fine tuning because currently Scoold will search each object on all of its data fields, meaning that if those 2 user objects have some data inside them containing "qt" then they will appear in the results.

Given that the search should help finding answers and avoiding similar questions, the expected behavior from our point of view would be: search will seek given substrings only in user accessible text like tags, q/a text, comments etc.

**Comment by albogdano** [comment]
The plan is to modify search queries so they match only the most important data fields but I have to be careful not to restrict the power of advanced search queries.

**Comment by albogdano** [comment]
I fixed the actual issue but I will keep this open because I will do some more work to improve search results.

**Comment by albogdano** [comment]
**Idea:**
- Search the answers for given keywords and present the parent question in the search results.

**Comment by b-morgenthaler** [comment]
From my perspective I don't see an additional value in searching only answers (at least this is how I understood your idea). If "search in answers only" is an extra feature (default would search in questions, answers, comments, tags and some user data) then I'm fine.

**Comment by albogdano** [comment]
That is exactly what the idea was - search for content not only in questions but also in their answers, then display the parent question in results.

**Comment by albogdano** [comment]
I've just pushed 6e90ceb which should make search better and search should take into account the contents of answers and comments within a question. Closing for now...
