### ISSUE TITLE
Any plans to support like API?

### ISSUE THREAD

**Issue by cjchand** [Erudika/scoold#241]
I see there is a like API (`/api/posts/{id}/like`), but the corresponding code in `ApiController.java` is:

```	
        @PutMapping("/posts/{id}/like")
	public void favPost(@PathVariable String id, HttpServletRequest req) {
		badReq("Not supported");
	}
```

Any ETA on when this will be supported?

**Comment by albogdano** [comment]
That is a Scoold Pro-only feature so no plans to add it to Scoold.

**Comment by cjchand** [comment]
Whoops. That explains it, then. Thanks!
