### ISSUE TITLE
Unable to login in 1.43.0

### ISSUE THREAD

**Issue by mzch** [Erudika/scoold#242]
When upgrading `scoold` from `1.42.1` to `1.43.0`, Users can't login.
Message is `Authentication failed or was canceled.` and no error in pa.ra.log.

Para: `1.38.4`
JDK: OpenJDK `11.0.9.1`
OS: Debian `10.9`.

**Comment by albogdano** [comment]
Hi Koichi,
How exactly do the users login (social login, email & password, etc.)?

**Comment by mzch** [comment]
Email & Password login.
In `1.42.1` I can login successfully.

**Comment by albogdano** [comment]
Fixed in `1.43.1`. Thank you for reporting this Koichi!
