### ISSUE TITLE
Enhance tag filter with additional AND relation between tags

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#243]
When I filter for tags like "faq" and "it" the logical behavior for the result is "OR". So every question with "it" or "faq" (including "it" and "faq") is presented. 

Additionally, a logical "AND" behavior for tag filter would be nice so that - in the example above - only questions with "it" and "faq" tags are presented as filter results.

BTW: searching for both tags seems to show only question with "it" and "faq", which is a possible "workaround"

**Comment by albogdano** [comment]
The actual query syntax for that is `tags:(+faq +it)` but I will probably add a switch button "Match all / Match any"
