### ISSUE TITLE
default question tag not used

### ISSUE THREAD

**Issue by b-morgenthaler** [Erudika/scoold#245]
Hi, with update to 1.43.2 on our test system, I noticed that the default question tag configured with

> para.default_question_tag = "test"

is not showing up when a new question is asked. I think this was also true with version 1.43.1...

>Scoold Pro
Scoold version: 1.43.2
Production mode: true
Para app: app:scoold
Para version: 1.38.4
Para endpoint: http://localhost:8080

**Comment by albogdano** [comment]
You mean it's not visible in the tags area? Yes, this hasn't been implemented yet. The default tag will be added to questions which are posted without any tags.

**Comment by b-morgenthaler** [comment]
I didn't mean the tags area, I meant the tag list when clicking "ask question".

You're right, a question without a tag gets the default tag after saving (I only added questions for testing with user defined tags).
I could have sworn that the tag was visible in the tag list by the time you click on "ask question"...

Sorry, for the confusion.

**Comment by albogdano** [comment]
I also meant the tag area under "Ask question" form. So you suggest that the default tag should appear in tag autocomplete list when selecting tags for a new question? Or, that the default tag should be visible as a selected tag when opening the new question form?
If the default tag was never used before, then it will not appear as a suggested tag because it doesn't exist yet.

**Comment by b-morgenthaler** [comment]
The latter: I assumed (and expected) the default tag should be visible as a selected tag when asking a new question. If it's the first question after configuration of a default tag, I understand and would not expect it to be showing up in tag autocomplete list. After saving the default tag is part of the overall tag list.

**Comment by albogdano** [comment]
Ok, got it! I'll make it happen.
