### ISSUE TITLE
vote_locked_after_sec is set to same value as vote_expires_after_sec

### ISSUE THREAD

**Issue by cjchand** [Erudika/scoold#248]
Expected behavior:
Setting for vote_locked_after_sec is reflected in votes recorded in the DB

Observed behavior:
The vote_locked_after_sec value in the vote is exactly the same as the vote_expires_after_sec value

Relevant info:
Looking in VoteController.java, it seems there's a copy/paste error: 

```
	public VoteController(ScooldUtils utils) {
		this.utils = utils;
		this.pc = utils.getParaClient();
		expiresAfter = Config.getConfigParam("vote_expires_after_sec", null);
		lockedAfter = Config.getConfigParam("vote_expires_after_sec", null);
		expiresAfterSec = NumberUtils.toInt(expiresAfter, Config.VOTE_EXPIRES_AFTER_SEC);
		lockedAfterSec = NumberUtils.toInt(lockedAfter, Config.VOTE_LOCKED_AFTER_SEC);
	}
```

Note how`lockedAfter` is set to `vote_expires_after_sec`, where I suspect it should be `vote_locked_after_sec`.

**Comment by albogdano** [comment]
Oops! You are absolutely correct. Fixed.

**Comment by cjchand** [comment]
Thanks!
