### ISSUE TITLE
How do I provide application.conf while debugging with Eclipse

### ISSUE THREAD

**Issue by dheeraj-thedev** [Erudika/scoold#249]
While running Jar file i am able to pass config.file=application.config but as i run it through eclipse it seems that it is not using the config file that i am passing.

**Comment by albogdano** [comment]
Just set the system property config.file=path/to/application.conf inside
Eclipse when executing the run command

**Comment by dheeraj-thedev** [comment]
Thanks it resolved the issue thanks
