### ISSUE TITLE
Posting a reply using Scoold API returns 500 response but still creates reply

### ISSUE THREAD

**Issue by gebailey** [Erudika/scoold#251]
I'm writing a script that populates a Scoold instance with questions and answers from a collection of markdown files.

Para version:  `v1.39.1`
Scoold version:  `v1.43.3`

I'm creating a question with a POST request to `/api/posts` with the body:

```
{
  "type": "question",
  "title": "Sample question title",
  "body": "Sample question body",
  "tags": [
    "imported"
  ]
}
```

The response from the above request is **201**, and I'm saving the `id` from the above request.

I then attempt to populate an answer to the newly created question using a second POST request to `/api/posts` with the body:

```
{
  "type": "reply",
  "parentid": "1319360724245417984",
  "title": "Sample question title",
  "body": "Here is the answer"
}
```

The response to this request is a **500**, but if I navigate the Scoold list of questions, I can see the "Here is the answer" listed as an answer to the question I created.

My question is how to diagnose the **500** response code; it's not clear if I'm providing the answer in the correct form.  If there's additional documentation for how to use the API (other than "apidocs") I'm happy to read that.  Thanks!

**Comment by albogdano** [comment]
Thanks @gebailey - the bug is fixed now in the `master` branch.
