### ISSUE TITLE
problem with sign up

### ISSUE THREAD

**Issue by szheng67** [Erudika/scoold#253]
Hi I deployed scoold to heroku and set up smtp following these steps [here](https://github.com/Erudika/scoold/blob/master/README.md#smtp-configuration). The application is running but I cannot sign in to an account. When I tried to sign up for an account it shows that a confirmation email is sent but I don't receive one. Anyone know what's wrong?

**Comment by albogdano** [comment]
You have not configured SMTP properly. You need a real SMTP server with a username and password. After configuring it you can resend your email confirmation and log in.

**Comment by szheng67** [comment]
I'm using gmail smtp server. I'm able to sign in using the same credentials from gmail.com and I enabled "allow less secure app", but it's still failing.
