### ISSUE TITLE
Comments that are passed the character limit are still allowed to be submitted

### ISSUE THREAD

**Issue by MidnightMailman** [Erudika/scoold#262]
I think there should be a better warning for the user if the comment is past the 255 character limit. My preference is either the button becomes disabled, or there is a modal or popup warning that says the message is too long. A bit of a nitpick I know. I am happy to know that for now I can just increase the character count for the comment.

**Comment by albogdano** [comment]
This only happens in Scoold Pro and I fixed it just now.
