### ISSUE TITLE
Conflict para_uri and oath_redirect_uri.

### ISSUE THREAD

**Issue by hhhhub000** [Erudika/scoold#263]
I used Docker to set up a para server and a scoold server.
They communicate with each other host name "para" and "scoold" using `docker network create`.

Then, I wrote `para.endpoint = "http://para:8080"` in the application.conf of scoold.
But, OAuth is faild, because para:8080 is local address.

So, I wrote `para.endpoint = "http://localhost:8080"`.
But, Scoold was following error occured
`2021-09-08 09:50:19 [ERROR] No connection to Para backend. Retrying connection in 10s (attempt 1 of 10)...`
because scoold and para are other host(container).

Is there a way to set the OAuth redirect URI and the para URI each?

Sorry for my poor english.

**Comment by albogdano** [comment]
Try setting `para.security.redirect_uri` to be your public Para URL and keep `para.endpoint = "http://para:8080"`

**Comment by hhhhub000** [comment]
It works fine!
Thanks for the quick answer!
