### ISSUE TITLE
Injection in search query

### ISSUE THREAD

**Issue by fpellet** [Erudika/scoold#267]
Hello,

Looking at the logs, I see errors like:  
`[ERROR] 400 - Invalid query string syntax q=properties.space:"scooldspace:default" AND question or <225> in request GET http://back:8080/v1/reply/search/default?q=properties.space%3A%22scooldspace%3Adefault%22+AND+question+or+%3C225%3E&type=reply`  

The problem is that special characters are not escaped.  (https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)   
As a result, it produces errors, the user doesn't see his search and potentially, it can produce security holes.

Maybe you need to modify `ScooldUtils.sanitizeQueryString` to do this.  

If it's ok for you, I can work on this issue.

**Comment by fpellet** [comment]
it's not enough  
Example: `(42`

I think you should add: `.replaceAll("\\\\", "").replaceAll("[\\?<>]", "").replaceAll("([\\(\\)\\+\\-&!\\{\\}\\[\\]\\^\"~:\\|])", "\\\\$1")`

**Comment by albogdano** [comment]
We don't want to escape all those symbols because they are used for constructing more complex queries and are part of the Lucene query syntax. For now this should do and I don't see any security issue here.

**Comment by fpellet** [comment]
Ok, I understand.  
It may be missing a feedback to the user in case of a bad request.  
We could display an error message inviting him to correct his request instead of displaying no result.
