### ISSUE TITLE
Allow to use Cloudinary to manage avatars

### ISSUE THREAD

**Issue by fpellet** [Erudika/scoold#279]
Hello,

For a non-developer audience, gravatar as default image is fine, but not more.
For a public website, allowing arbitrary urls is hard to moderate. The images can be big and a bad person could return not always the same image and spy on users by hosting on his server.
Allowing file uploads is also problematic, especially because of the weight of the images.

I therefore propose to add the possibility to use the Cloudinary service.
The user can then send his image and it is persisted on this SaaS service. 
The advantage is that it is possible to apply optimizations on the images to reduce the weight and the size according to the pages.
It is also possible to apply moderation modules on the image content.

I propose to implement it but I would like to know if it is an acceptable feature.

**Comment by albogdano** [comment]
Feel free to implement this if you are still interested.
