### ISSUE TITLE
The theme changing doesn't works

### ISSUE THREAD

**Issue by ProfNpc** [Erudika/scoold#281]
I was using the version 1.45.0 of scoold and I have configured one custom theme for my use.

![image](https://user-images.githubusercontent.com/60479274/145085182-06c40c6a-4caa-45a1-a330-37a91db2dc2f.png)
When I moved to 1.47.0, I noticed that the theme changing is not working anymore.

After clicking "APPLY", the top bar does not change color.

![image](https://user-images.githubusercontent.com/60479274/145086199-f8fc073d-8875-4348-8621-d99d4f9438f0.png)
I maked an investigation and discover that the view "base.vm" contains one insertion of css that is processed by the method getInlineCSS()

![image](https://user-images.githubusercontent.com/60479274/145092437-2f70189d-ba8b-4239-85b7-678bdbd8782a.png)
![image](https://user-images.githubusercontent.com/60479274/145092477-7b7ec1b6-40d3-4c26-8deb-555aec416991.png)
I noticed this method was changed recently.

![image](https://user-images.githubusercontent.com/60479274/145092743-ed073451-59c2-444d-8ee3-1b122909821f.png)

The call to method `StringEscapeUtils.escapeEcmaScript(loadedTheme)` change  the code css from 

`/**** RED THEME ****/\n/* buttons, headings and links */\na, h1, h2, .dropdown-content li>a, .dropdown-content li>span { color: #c62828; }\n.btn, .btn-large, .navbtn-hover { background-color: #37474f; }\n.btn:focus, .btn-large:focus, .btn-floating:focus { background-color: #37474f; opacity: 0.7; }\n.filter-active { background-color: #c62828; color: white; }\n\n/* nav bar and footer */\nbody, footer.page-footer { background-color: #333333; }\n.navbar-color { background-color: #c62828; }\n\n/* switches and inputs */\n[type="radio"]:checked+span:after, [type="radio"].with-gap:checked+span:after { background-color: #c62828; }\n[type="radio"]:checked+span:after, [type="radio"].with-gap:checked+span:before,\n[type="radio"].with-gap:checked+span:after { border: 2px solid #c62828; }\n.switch label input[type=checkbox]:checked+.lever { background-color: #ff5f52; }\n.switch label input[type=checkbox]:checked+.lever:after { background-color: #8e0000; }\n[type="checkbox"].filled-in:checked+span:not(.lever):after { border: 2px solid #c62828; background-color: #c62828; }\n[type="checkbox"]:checked+span:not(.lever):before { border-right: 2px solid #c62828; border-bottom: 2px solid #c62828; }\n\n/* progress bars */\n.progress .indeterminate { background-color: #c62828; }\n.progress { background-color: #ff5f52; }\n\n/* tabs */\n.tabs .tab a:hover, .tabs .tab a.active, .tabs .tab a { color: #c62828; }\n.tabs .indicator { background-color: #c62828; }
`

to 

`\/**** RED THEME ****\/\n\/* buttons, headings and links *\/\na, h1, h2, .dropdown-content li>a, .dropdown-content li>span { color: #c62828; }\n.btn, .btn-large, .navbtn-hover { background-color: #37474f; }\n.btn:focus, .btn-large:focus, .btn-floating:focus { background-color: #37474f; opacity: 0.7; }\n.filter-active { background-color: #c62828; color: white; }\n\n\/* nav bar and footer *\/\nbody, footer.page-footer { background-color: #333333; }\n .navbar-color { background-color: #c62828; }\n\n\/* switches and inputs *\/\n[type=\"radio\"]:checked+span:after, [type=\"radio\"].with-gap:checked+span:after { background-color: #c62828; }\n[type=\"radio\"]:checked+span:after, [type=\"radio\"].with-gap:checked+span:before,\n[type=\"radio\"].with-gap:checked+span:after { border: 2px solid #c62828; }\n.switch label input[type=checkbox]:checked+.lever { background-color: #ff5f52; }\n.switch label input[type=checkbox]:checked+.lever:after { background-color: #8e0000; }\n[type=\"checkbox\"].filled-in:checked+span:not(.lever):after { border: 2px solid #c62828; background-color: #c62828; }\n[type=\"checkbox\"]:checked+span:not(.lever):before { border-right: 2px solid #c62828; border-bottom: 2px solid #c62828; }\n\n\/* progress bars *\/\n.progress .indeterminate { background-color: #c62828; }\n.progress { background-color: #ff5f52; }\n\n\/* tabs *\/\n.tabs .tab a:hover, .tabs .tab a.active, .tabs .tab a { color: #c62828; }\n.tabs .indicator { background-color: #c62828; }`

When I was debugging the application, I change the content of `loadedTheme `variable to the previous value and the theme was changed.

![image](https://user-images.githubusercontent.com/60479274/145095065-c94943b7-bf57-4cd6-800c-c673f59c11a4.png)

**Comment by albogdano** [comment]
Ok, thank you for the detailed report of this bug! I did realize how that
might break the comments inside CSS. Will fix tomorrow.

**Comment by albogdano** [comment]
Fixed. Expect a new release today or tomorrow..
