### ISSUE TITLE
"Toggle fullscreen" when writing question/answer is now partially broken

### ISSUE THREAD

**Issue by klillas** [Erudika/scoold#293]
We updated our scoold server now, I think we were two releases behind latest or something similar.

When writing a Q/A using the "Toggle fullscreen" and "Toggle side by side" options we are seeing some behavior which was not happening before the update.

There are no scrollbars on the left side, and you cannot mouse scroll. The right side (preview) is fine.

The left side is not extended to use the available width of the monitor, it seems to have a default width and stay at that no matter what (best seen on ultrawide displays). This width seems to be much narrower than the actual width of the window, which in turn seems hidden behind the preview side (right side)

When writing a long line the text disappears "under" the right side (preview).

![image](https://user-images.githubusercontent.com/7252976/160854899-21f042a8-974e-48f6-903d-9c34b2368f20.png)

**Comment by albogdano** [comment]
It is also possible that you have an old version of styling file of the text editor plugin. Can you do a hard refresh with <kbd>Ctrl + Shift + R</kbd>

**Comment by klillas** [comment]
Thanks, it works fine after that.
