### ISSUE TITLE
ClassCast after login

### ISSUE THREAD

**Issue by Teg79** [Erudika/scoold#3]
After a successful login with MS I get this error using Scoold (every page):
2017-05-15 17:16:16 [DEBUG] GET /v1/_id/775008390567956480:profile, params: null
2017-05-15 17:16:16 [WARN ] EXCEPTION 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.ClassCastException: com.erudika.para.core.Sysprop cannot be cast to com.erudika.scoold.core.Profile
at com.erudika.scoold.utils.ScooldUtils.checkAuth(ScooldUtils.java:93)

The server always respond with HTTP 500

**Comment by albogdano** [comment]
This is most probably because you're missing `para.core_package_name = "com.erudika.scoold.core"` in your config. I know this should be set by default and will be fixed in the next patch.



Alex Bogdanovski

**Comment by Teg79** [comment]
This fixed the problem, thanks
