### ISSUE TITLE
Users on default space disappears, etc.

### ISSUE THREAD

**Issue by showaid** [Erudika/scoold#30]
Hi @albogdano,

I am currently testing v1.28.9 and found some issues.

1. User on default space disappeared
It seems that users on default space doesn't show.
![screenshot - 2018-02-13 11_07_55](https://user-images.githubusercontent.com/1582582/36130096-274b498c-10ae-11e8-805f-18a083bf3541.png)
When I look into this symptom in IDE debug mode, there is a difference between query string(qs) of default space and custom space(e.g. SpaceA).
- default space : ""
- custom space: "properties.spaces:"scooldspace:spacea:SpaceA""

2. Inappropriate value shows in the user search box
![screenshot - 2018-02-13 11_14_16](https://user-images.githubusercontent.com/1582582/36130252-13d81820-10af-11e8-960a-9e1327a3fce7.png)

3. 404 page not found when I search at side-nav
![screenshot - 2018-02-13 11_18_27](https://user-images.githubusercontent.com/1582582/36130331-a2acf976-10af-11e8-8690-348802904704.png)

Thank you for your dedication as always!

**Comment by albogdano** [comment]
Thanks for reporting these HyunWoo! Can you please have a quick look and if you don't find any other issues I'll release the new patched version.

**Comment by showaid** [comment]
These have fixed! Great work!
I'll report if I find anything!
Thank you!
