### ISSUE TITLE
Bind DN not used when performing ldap search-based authentication

### ISSUE THREAD

**Issue by kobus-v-schoor** [Erudika/scoold#327]
Hi there, I'm attempting to set up a local Para + Scoold deployment with AD authentication. At the moment I can't get any LDAP authentication to work because it seems like the bind_dn and bind_pass attributes are being ignored. I verified this by setting up a test ldap server (using the `bitnami/openldap` docker image). My Scoold ldap configuration is as follows:

```
scoold.security.ldap.server_url = "ldap://ldap:1389/"
scoold.security.ldap.base_dn = "dc=example,dc=org"
scoold.security.ldap.bind_dn = "cn=admin,ou=users,dc=example,dc=org"
scoold.security.ldap.bind_pass = "adminpassword"
```

In the logs of the ldap server, you can see the bind DN/pass not being passed along (these logs were generated when attempting to log in using ldap on Scoold):

```
62deb147.148f7ec0 0x7f05c11c4700 conn=1049 fd=12 ACCEPT from IP=10.242.132.150:38336 (IP=0.0.0.0:1389)
62deb147.1496e3a1 0x7f05c09c3700 conn=1049 op=0 BIND dn="" method=128
62deb147.14984e53 0x7f05c09c3700 conn=1049 op=0 RESULT tag=97 err=0 qtime=0.000012 etime=0.000109 text=
62deb147.14e93a60 0x7f05c11c4700 conn=1049 op=1 SRCH base="dc=example,dc=org" scope=2 deref=3 filter="(cn=asd)"
62deb147.14eaa05e 0x7f05c11c4700 conn=1049 op=1 SEARCH RESULT tag=101 err=0 qtime=0.000019 etime=0.000137 nentries=0 text=
62deb147.150990e1 0x7f05c09c3700 conn=1049 op=2 UNBIND
```

For reference, a successful bind looks like this:

```
62deb325.159603fa 0x7f05c09c3700 conn=1055 fd=12 ACCEPT from IP=10.242.132.150:43486 (IP=0.0.0.0:1389)
62deb325.1599400d 0x7f05c11c4700 conn=1055 op=0 BIND dn="cn=user01,ou=users,dc=example,dc=org" method=128
62deb325.159b560b 0x7f05c11c4700 conn=1055 op=0 BIND dn="cn=user01,ou=users,dc=example,dc=org" mech=SIMPLE bind_ssf=0 ssf=0
62deb325.159c4143 0x7f05c11c4700 conn=1055 op=0 RESULT tag=97 err=0 qtime=0.000017 etime=0.000234 text=
62deb325.15c0aa4c 0x7f05c09c3700 conn=1055 op=1 UNBIND
62deb325.15c196ef 0x7f05c09c3700 conn=1055 fd=12 closed
```

Can you see something that I'm maybe doing wrong? Any help would be greatly appreciated.

Scoold version: 1.50.1
Para: v1.46.1

**Comment by albogdano** [comment]
I'm confused - do you want to connect to AD or LDAP. For AD you need to specify:
```
# add this ONLY if you are connecting to Active Directory
scoold.security.ldap.active_directory_domain = "company.org"
```
For details about AD specifically, [see here](https://github.com/Erudika/scoold#active-directory-ldap).

Now, if you want to connect to LDAP, you should probably ignore `bind_dn` and `bind_pass`.
User credentials are supplied through the Scoold login form.

**Comment by kobus-v-schoor** [comment]
Hi @albogdano, thanks for getting back to me. In production I want to connect to AD, so I initially set it up according to the documentation (with the extra stuff for AD) but I couldn't get it to work and I suspect it was due to the bind DN not getting used. So, to debug the issue I set up a normal LDAP server to check how Para is connecting to the LDAP server (and then I saw the bind dn wasn't getting passed through). The bind DN and password should still be used if specified, even it's not AD right?

**Comment by albogdano** [comment]
If you connect to AD `bind_dn` and `bind_pass` are simply ignored. These properties are only used for regular LDAP connections and are sent to Para every time Scoold starts up. Para handles all LDAP requests, then redirects back to Scoold. Hope that makes sense.

**Comment by kobus-v-schoor** [comment]
Thanks for the explanation - would it be possible to set up Para to not ignore the bind dn and password for AD connections? Our AD setup does not allow anonymous searches (security risk), and the users are not all under the same OU so we can't make use of the user template to directly bind them. We need Para to search for the user (using the provided bind credentials), and then attempt to bind using the user login credentials

**Comment by albogdano** [comment]
The search is not going to be anonymous because a bind operation is performed first, using the given credentials. The AD interface available in Spring LDAP does not allow the use of `bind_dn` and `bind_pass` - that's only possible for regular LDAP. But the same is valid there - first a bind is performed (i.e. user is authenticated) then the search happens.

**Comment by kobus-v-schoor** [comment]
Maybe I'm missing something here, but how I understand it the process should be is the following (this is also what I've seen other services making use of LDAP auth is using):

- Para (Scoold) is provided with a `bind_dn` and `bind_pass` that has readonly search permissions on the directory
- A user attempts to log in with the username `user01` - para then binds to the directory using `bind_dn` and `bind_pass` (**not** the user's credentials, because we don't know their DN yet) so that it can search for the user. 
- Once Para has found the DN for the user (e.g. `cn=User Name,ou=users,dc=example=dc=org`), it attempts to bind to the user's DN using the password provided by the user (**not** `bind_pass`).

At the moment it looks like Para is not using the `bind_dn` and `bind_pass` parameters for the search, it attempts to directly bind using the user's provided credentials. The problem with this is, since Para doesn't know the DN for the user yet (which isn't necessarily derived directly from the username, it could include the user's real name e.g. `cn=First Last,...`) the bind fails and then the authentication doesn't go through.

**Comment by kobus-v-schoor** [comment]
Hi @albogdano, I got it to work, sorry for the confusion - I didn't realize that it was possible to bind on AD not just using your full DN, but also using just your email address and password.

For those maybe stumbling across this in the future, when AD mode is enabled on Para it will attempt to bind using `your-email@ad-domain.com` and your password. Since it can bind using just your email it doesn't need a separate bind dn and password (as one would need for OpenLDAP).

**Comment by albogdano** [comment]
Yes, exactly. LDAP is indeed a bit confusing at times. Thank you for the detailed notes! :+1:
