### ISSUE TITLE
Beginner's Issue: Running Scoold locally with Para

### ISSUE THREAD

**Issue by TrishaJariwala** [Erudika/scoold#33]
I want to run a cloned Scoold project locally with Para.
To describe my struggle so far, I've cloned the Scoold project from GitHub and made a new app on paraio.com and I have also saved the access & secret keys.
What next?
Should I mention my Para keys in app.json or create an application.conf file? If either of the files is to be made then my keys should be mapped to which attribute/variable? And how do I run my project locally after that?

**Comment by albogdano** [comment]
@TrishaJariwala Yes, add the keys to your `application.conf` file as described in the docs:
```
# access key for your Para app
para.access_key = "app:scoold"
# secret key for your Para app
para.secret_key = "*****************"
```
**Do not edit `app.json`!** It is used by Heroku to initialize a new dyno. 
You then run Scoold with `java -jar -Dserver.port=8000 -Dconfig.file=./application.conf scoold.jar` if you have downloaded the JAR file OR `mvn spring-boot:run` inside the cloned project folder.

**Comment by TrishaJariwala** [comment]
Thank you, @albogdano 
It worked. Now Para is connected with my Scoold project.

**Comment by TrishaJariwala** [comment]
What changes should be made in order to enable Gmail (Google) sign in, in
Scoold via Para? I've already generated the Client ID credentials via
Google Developers. What next?
And what if I want to integrate my website's API with Scoold to sign in via
my website just like Google, Facebook?
Please help me out.

**Comment by albogdano** [comment]
Edit `application.conf` and add:
```
# Facebook - your Facebook app id
para.fb_app_id = "123456789"
# Google - your Google client id
para.google_client_id = "123-abcd.apps.googleusercontent.com"
```
What website API are you talking about? OAuth 2.0? Scoold can use generic OAuth 2.0 for authentication or one of the other supported identity providers, listed here: http://paraio.org/docs/#034-api-jwt-signin

**Comment by TrishaJariwala** [comment]
I've already added my Google Client API to "para.google_client_id"
attribute in the application.conf file in my project, but it is not working.
It is showing the following error message shown in the attached PNG file.
Do I need a "para.host_url" or anything else needs to be added or changed
in the project to function sign in via Google(Gmail)?

**Comment by albogdano** [comment]
Yes, of course, all configuration properties shown in `README.md` are required and need to be set properly. `para.host_url` must be set and **whitelisted** in the Google API console as a redirect URL.

**Comment by TrishaJariwala** [comment]
If I am running the Scoold project locally on port 8000, what should be the
value for "para.host_url" in my application.conf file?
And what URL shoul be whitelisted in the Google API console as a redirect
URL?
The README.md  file states that the URL should be para.host_url = "
https://your.scoold.url" or para.host_url = "https://your-scoold-domain.com";
what would be the URL in my case if I am running Scoold locally from
*http://localhost:8000/
<http://localhost:8000/>*?

**Comment by TrishaJariwala** [comment]
Thank you so much, sir.


I have set *para.host_url = "http://localhost:8000 <http://localhost:8000>"
*in application.conf file.
And in Google Client ID for Web application
-->  Authorized JavaScript origins :  http://localhost:8000 ,
https://scoold.public.url
-->  Authorized redirect URIs :  http://localhost:8000

This works almost great, as it is able to open the Gmail sign in page and
successfully accepts (valid) credentials for a Google account.
But, after signing in successfully with Google, the webpage displays the
error, "*Authentication failed or was cancelled*", & the URL in the browser
goes as "*http://localhost:8000/signin?code=3&error=true
<http://localhost:8000/signin?code=3&error=true>*"
& so, it seems like that Google account is not signed in with Scoold for
some reason. (Even though that Google account is signed in successfully in
the browser after providing credentials for Scoold)
And the unsuccessful sign in of Scoold via Google prompts like the attached
screenshot.

**Comment by albogdano** [comment]
![image](https://user-images.githubusercontent.com/346873/36479480-86bf65f6-1711-11e8-99ef-3e8204479590.png)

**Comment by TrishaJariwala** [comment]
IT'S RUNNING SUCCESSFULLY..!!!!!!!!!!
It is finally integrated and it is working successfully.!!
Thank you so much for all your help.

**Comment by TrishaJariwala** [comment]
Can I use credentials from an external database (for example, MySQL
database) to log in that user in Scoold?
If yes, how can I connect my database with Scoold to fetch/verify
credentials from the database and log in those users?
What properties do I have to set & what other methods will I have to
modify/implement?

**Comment by albogdano** [comment]
You can if your database is connected to an OAuth 2.0 or LDAP server.

**Comment by TrishaJariwala** [comment]
Can I use Para and MySql JDBC connection in the same code?

I have referred the below link:
https://medium.com/@joeclever/using-multiple-datasources-with-spring-boot-and-spring-data-6430b00c02e7

Please guide me for the same.

**Comment by albogdano** [comment]
Have a look at the [SQL DAO](https://github.com/Erudika/para-dao-sql). You can use it to store data in MySQL. It's a relatively new plugin and may contain some bugs.

**Comment by TrishaJariwala** [comment]
Thank you, Alex! That is a great plugin.

But,
Reframing my query:

I want to *retrieve & verify* username & password from an existing MySQL
database, to sign in Users (with that username & password) in my Scoold app.
Will this SQL DAO plugin provide this functionality as well? If not, how
else can I do that?

**Comment by albogdano** [comment]
It won't be a straightforward process but it could be possible to use the SQL DAO plugin with MySQL and export the users from your existing database to the Scoold app table. But there's no simple way for Scoold to take your existing DB table of users and just use it for authentication. To achieve this your DB must be linked to a OAuth 2-compatible identity provider service or LDAP. Scoold supports both LDAP and generic OAuth 2 authentication.

**Comment by TrishaJariwala** [comment]
Hello Alex,
I've successfully done the login process of Users from my existing MySQL
database (using JDBC).
The users are successfully signed in, but I am facing two issues:

   1.  Every time I sign in any user using those credentials, I have to go
   to Para and activate that user and sign in him to Scoold again.
   2.  I am unable to change the default name of the user in user's
   profile, the default name is something like "ParaObject *********". I want
   to change this name to that user's respective name from my database's
   username column.

How can I change these values and which files/methods do I need to modify
to acquire these changes?

I would be glad if you would help me with this.

**Comment by albogdano** [comment]
On the first point, you have to actually send an email to users to confirm their email address. To disable this set `para.security.allow_unverified_emails = true`. Activation is only done once then the user is set `active = true`.

On the second point, all profile objects have the same name as the `User` object, i.e. the name of the user. In your case you might be doing something wrong. Users and profiles are always created automatically, not manually.

**Comment by TrishaJariwala** [comment]
Hello Alex,
I am facing an issue in updating Scoold's user's avatar with an explicit
image (excluding Gravatar image).
I have noticed that image addresses with "*https*://xxx" are only accepted
for picture upload; if the image address goes with "*http*://xxx" it is not
accepted or uploaded and reflects a cracked/corrupted image icon in place
of the user avatar.
Have you set any property in the code for this, that secured images with
"https://" will only be accepted and others will not be uploaded? If so,
guide me through this property and help me set an image with the address
beginning with "http://xxx".

Regards,
Trisha.

**Comment by albogdano** [comment]
This is because of the Content Security Policy (CSP) header. HTTP URLs are blocked by default. Either upload pictures to a secure location or edit/disable the CSP with `para.csp_header = "new_value"` or `para.csp_header_enabled = false`.

**Comment by TrishaJariwala** [comment]
Thank you, Alex. This really helped. 🙂
The images are successfully displayed on the user's profile, but Para's
user object still displays a corrupted image icon.


​

**Comment by TrishaJariwala** [comment]
Is there a solution for the same?

**Comment by albogdano** [comment]
The picture in the Para `user` object should be synced with the one in the Scoold `profile` object on login. You don't have to do anything.

**Comment by albogdano** [comment]
If you want to see http://** pictures in ParaIO.com - sorry that's not possible.

**Comment by TrishaJariwala** [comment]
Okay, Alex.
Thank you for informing this.

**Comment by jmakanjuola** [comment]
Hi Alex,

1:  What should callback value be for OAuth in Github? https://paraio.com:8080 or http://127.0.0.1:8000/hub/oauth_callback? 

So far the Scoold Project is setup and it's runninng locally. I've define para key/values in `scoold/application.conf` inside my running Kubernetes cluster.

 For example, 
`para.security_signout_success: /signin`
  `para.security_signin_failure: /signin` 

Another example, in an attempt to use Github to authenticate into scoold locally, inside of Github, I created an OAuth Client ID and Client Secret  and assigned the Client ID & Client Secret values to `para_gh_app_id` & `para_gh_secret` as suggested in your documentation.


para_gh_app_id: Client ID {{ .Values.para_gh_app_id }}
para_gh_secret: Client Secret {{ .Values.para_gh_secret }}

when I refresh scoold nothing no changes the scoold signin remains unchanged.

**Comment by albogdano** [comment]
Why do you set `para_gh_app_id` instead of `para.gh_app_id`? The underscore notation is only valid for environment variables, e.g. `export para_env=production` and you shouldn't use it inside `application.conf`

**Comment by jmakanjuola** [comment]
I don't think that the issue. Below are the actual key and values of my actual file for GitHub

`para.gh_app_id: {{ .Values.para.gh_app_id }}`
`para.gh_secret: {{ .Values.para.gh_secret }}`

**Comment by albogdano** [comment]
What is this `{{ .Values.para.gh_app_id }}`? After each change in `application.conf` you have to restart Scoold.
