### ISSUE TITLE
Updating profile picture/avatar of another user as administrator temporarily updates profile picture in menu bar.

### ISSUE THREAD

**Issue by rberends** [Erudika/scoold#330]
Hey there!

Found a small issue, quite inconsequential, but figured I'd report it anyway.

If, as an administrator, you update the profile picture through the user page of another user (change profile picture - add) it also updates the profile picture of your own profile button in the menu bar. 

![image](https://user-images.githubusercontent.com/59354731/182802513-432f4871-d479-4fc1-bac0-79f894f35843.png)

This resets after navigating away from the page. So no permanent changes.

Maybe a quick check on the page to make sure the user page matches the user currently logged in would resolve this?

**Comment by albogdano** [comment]
Thanks for reporting this bug, Roel! Fixed.
