### ISSUE TITLE
Allow for update notifications to "subscribed" questions

### ISSUE THREAD

**Issue by rberends** [Erudika/scoold#341]
Hey there,

A feature request from our users. It would be great if there was an option to flag a question as "interesting" which in turn would then send notifications, for example via e-mail when there is activity on said questions. Even if they are asked by someone else.

**Comment by albogdano** [comment]
That functionality already exists - you can subscribe to activity around any question by checking this checkbox under the text area for writing answers:

![Screenshot from 2022-09-09 01-40-44](https://user-images.githubusercontent.com/346873/189238661-cd1e98f2-de89-460c-b326-d1bae848bc89.png)
