### ISSUE TITLE
Downvotes on comments seem permanent

### ISSUE THREAD

**Issue by rberends** [Erudika/scoold#342]
Hey there, a small possible bug our users found. When placing downvotes on comments/reactions, leaving the page and returning, it seems it is impossible to undo a downvote in a way that would adjust the score of the comment. 

![image](https://user-images.githubusercontent.com/59354731/189140051-86ab33bd-5063-4d0c-9e06-c5cc5c41d811.png)

**Comment by albogdano** [comment]
I can't reproduce this issue. There is only a period of 30s in which you can amend the vote before it is locked.
