### ISSUE TITLE
Google Analytics or Tag Manager integration

### ISSUE THREAD

**Issue by ric2z** [Erudika/scoold#347]
Hello there,

I'm trying to set my instance up with either the Google Tag Manager, or with Google Analytics directly, but I don't see a config property for this purpose specifically. Is there an option that I'm missing or is my only option to modify the code?

Thanks!

**Comment by albogdano** [comment]
Google Analytics and the Tag Manager should work with Scoold by adding them as external scripts:
```
scoold.external_scripts.ga1 = "https://google.com/ga.js"
```
Additionally, you may have to configure the CSP security header to support the new script:
```
scoold.csp_connect_sources = "www.google-analytics.com www.googletagmanager.com accounts.google.com"
```

**Comment by ric2z** [comment]
@albogdano this is exactly what I needed – thank you
