### ISSUE TITLE
How to find frequently visiting users in scoold

### ISSUE THREAD

**Issue by Vinayak-Mahadev** [Erudika/scoold#348]
Is there any way to find out frequently visiting users in scoold via API or Para-cli?

**Comment by albogdano** [comment]
If you are asking about unauthenticated users, the answer is no but you could use something like Google Analytics to track visitors. If you are asking how to find the most active users in Scoold, try using the List Users API call and sort the results by :
```
GET /api/users?sortby=properties.lastseen&limit=20
```
Scoold does not provide any other data about the frequency of visits or logins.

**Comment by Vinayak-Mahadev** [comment]
Thank you
