### ISSUE TITLE
emoji not loading

### ISSUE THREAD

**Issue by jorgtledo** [Erudika/scoold#361]
Hello, I am using the opensource version and I have the following problem when loading the emoji

![image](https://user-images.githubusercontent.com/12876289/210905153-5792b3f0-4e3d-4801-b0dc-bc7b695f1e95.png)

![image](https://user-images.githubusercontent.com/12876289/210905209-749d1d34-ccaa-41eb-be3a-1607609b01d9.png)

The problem seems to be with picmo, I read that it could be an https problem

Thanks.
Regards.

**Comment by jorgtledo** [comment]
Hello, thanks for answering, I am using docker and docker-compose (from the repository), I am generating the image using the DockerFile and sending it to a private dockerhub, then the server is accessed by ip lan.

**Comment by albogdano** [comment]
The thing is that emojis are stored locally and are loaded without using an internet connection. Could it be because of that websocket error? Is that error shown because of some dev tools you are using? 
Check the network tab for any 404 errors when loading the emoji data from `/scripts/emojibase/data.json`

**Comment by jorgtledo** [comment]
Hi, I'm using the chrome developer console, I don't have any 404.

![image](https://user-images.githubusercontent.com/12876289/211063877-74a4a97e-fa5b-481d-af5d-b27ffec4d34e.png)
![image](https://user-images.githubusercontent.com/12876289/211063937-3b59d68b-8898-42fe-879f-09b35b91c7ce.png)

Websocket error also occurs on scoold demo site

![image](https://user-images.githubusercontent.com/12876289/211064115-a43d4de3-d94c-4d22-bdaa-d470e9ce9436.png)

Thanks

**Comment by jorgtledo** [comment]
I just deployed the docker image

erudikaltd/scoold:latest_stable

And I have the same problem, it doesn't seem to be something from my compilation but something from the picmo library, maybe the site is not https.

Do you always deploy to https? does it work for you in http?

Thanks.

**Comment by albogdano** [comment]
There is no strict requirement for HTTPS in order to get the emojis to work. For me, all emojis work on localhost even without internet. I guess I can try to update the picmo package and hope the new version contains fixes...

**Comment by albogdano** [comment]
Maybe the problem is that the address of your server is an IP address 10.1.6.3? Did you set `scoold.host_url` to be that same IP address? Maybe Chrome doesn't like the address.

**Comment by jorgtledo** [comment]
I updated to the latest version of picmo, replacing the .js and it didn't work

![image](https://user-images.githubusercontent.com/12876289/211068426-d0637688-a5b9-4755-a755-11bdddacdeca.png)

In firefox I have this error, I think I know what the problem is the WAF and the headers.

https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined

![image](https://user-images.githubusercontent.com/12876289/211068896-0853826a-9875-4320-bf62-91db154b3e70.png)

I'm going to try changing the headers to admit all insecure content

**Comment by albogdano** [comment]
Actually, I haven't thought about this scenario until now and I haven't seen that error before. If the only blocker is the loading of the data.json file, maybe I can embed it inside the other JS script which initialized the emoji picker [`emoji-picker.js`](https://github.com/Erudika/scoold/blob/master/src/main/resources/static/scripts/emoji-picker.js#L3)

**Comment by jorgtledo** [comment]
For me it is not the problem of loading the data.json file, it is that picmo wants to use WebCrypto and the browser does not allow the call because it is running on an insecure url, it works on localhost because browsers consider it a secure url, but an ip and a port seems to be insecure.

Anyway I'm going to try modifying the headers, but it seems that the use of WebCrypto (which uses picmo) is limited to secure urls and that's why it breaks with undefined

**Comment by albogdano** [comment]
Yes, I see. If you are only doing local development, can't you just map the address to localhost somehow or configure Docker to serve from localhost instead of that IP? If your goal is to host Scoold publicly on the internet, then maybe it's best that you configure HTTPS. 

I wish I could help but in this situation, my hands are tied.

**Comment by jorgtledo** [comment]
I understand and you are right, it is a third party library.

The objective is to use it internally for an organization, that is why it has a lan ip, we are going to solve the problem with https, to deploy it correctly, thank you very much for your support.
