### ISSUE TITLE
Add feedback form for "approve answer" action

### ISSUE THREAD

**Issue by Vinayak-Mahadev** [Erudika/scoold#363]
Can we collect feedback by clicking approve answer button? (possible we can keep this one in configuration)

Example: 
![image](https://user-images.githubusercontent.com/40711373/211470929-eb19f2e5-8ff7-45de-8c3f-7507ab02a976.png)

**Comment by albogdano** [comment]
This can be acheived with some JavaScript code but it is not available in Scoold yet.
