### ISSUE TITLE
rest api not working for "update user"

### ISSUE THREAD

**Issue by tony-jinwoo-ahn** [Erudika/scoold#365]
Hello, rest api for "update user" is described here, but not working:
https://live.scoold.com/apidocs#/users/patch_api_users__id_

I've tried several times changing nickname and email for specific user, but got 404 error.
can you show more detailed usage tutorial for this api? 

...And "changing password using rest api" seems not implemented, but it's listed in that api document. 
do you have any plan to implement "change password using rest api"?

Thank you.

**Comment by albogdano** [comment]
Could you show me your request body? Changing the user email has only just been implemented in `1.52.0` so make sure you get the latest version first. Passwords cannot be modified yet but you can try to overwrite the user with a `POST` request to change the password.

**Comment by albogdano** [comment]
The API now allows password changes: d1f6953d3ec5903c87ccf4439330cc386f2035f1

**Comment by tony-jinwoo-ahn** [comment]
Thank you for quick implementation!

**Comment by tony-jinwoo-ahn** [comment]
> you can try to overwrite the user with a POST request

When I use "POST" instead of "PATCH", I got error 405:
```
"message":"Request method &apos;POST&apos; not supported",
"status":"405"
```

**Comment by tony-jinwoo-ahn** [comment]
> Could you show me your request body? 

I tried Request body generated from here:
https://live.scoold.com/apidocs#/users/patch_api_users__id_
I used "curl -X PATCH ..." as it's generated from there.

I filled only "id" and "creatorid" as it's stored in DB, and left everything to "string", just to see if it changes nickname to "string" literally.
But got 404 error, and nothing changed.

Maybe I did something wrong?
I have a question. If I want to change nickname only, can I omit other items from the Request body? (e.g. picture, badges, etc)

**Comment by albogdano** [comment]
When you use the POST method you need to remove the id from the path, e.g. POST /api/users.
You can't change or modify the `id` property of users - that's managed by the Para backend. 
Also ignore the `creatorid` property which is also filled in for you.
There is no `nickname` property on the user profile object, only `name`.
You can do partial updates with only one property in the request body:
```
{
   "picture": "https://example/file.jpg"
}
```
If you get a 404 error that means that there is no user object with that id, so you are doing something wrong. See the list of users to get the actual id of the user you want to update.

**Comment by tony-jinwoo-ahn** [comment]
Thank you. I said nickname, but I meant ```name```, just to make sure it's not "id", sorry for confusing word.
I have a question. There's nested "name" inside "user" in the json body:
```
{
  "name": "string1",
  "user": {
    "name": "string2"
  }
}
``` 
what's difference between them? which one should I fill to change name of user?

**Comment by tony-jinwoo-ahn** [comment]
I tried, but failed.

Request body:
```
{
  "id": "me@email.com",
  "creatorid": "15264...",
  "name": "current_name",
  "user": {
    "id": "15264...",
    "identifier": "me@email.com",
    "name": "new_name",
    "email": "me@email.com"
  }
}
```

I tried:
```
curl -vvv -X POST "http://my-site/api/users" -H "accept: application/json" -H "Authorization: Bearer ..." -H "Content-Type: application/json" -d "{\"id\":\"me@email.com\",\"creatorid\":\"15264...\",\"name\":\"current_name\",\"user\":{\"id\":\"15264...\",\"identifier\":\"me@email.com\",\"name\":\"new_name\",\"email\":\"me@email.com\"}}"
```

I got:
```
400 Bad Request
{"message":"Failed to create user - 'identifier' cannot be blank; 'email' cannot be blank","code":400}
```

**Comment by albogdano** [comment]
The nested `user` object inside the response is just for extra information and cannot be modified. You can only modify the name of the main object, not the nested name. Para works with user objects of type `user` and Scoold works with `profile` objects. The two are different but both contain user information. The user id cannot be manually set to their email address as in your example. The correct request body would be something like this:

```
POST /api/users
{
   "identifier": "me@email.com",
   "name": "some name",
   "email": "me@email.com"
}
```
You will get a new object with a random numeric `id`, e.g. 12345, then to update:
```
PATCH /api/users/12345
{
   "name": "new name",
   "email": "new_address@email.com"
}
```

**Comment by tony-jinwoo-ahn** [comment]
Thank you, it works!
