### ISSUE TITLE
Can see two default spaces which leads to inconsistent questions list on the landing page

### ISSUE THREAD

**Issue by ajz007** [Erudika/scoold#368]
When I launch the app on my local environment I can see two default spaces named as - 'default' and 'Default Space'
I believe only 'Default Space' should be available.

![image](https://user-images.githubusercontent.com/59799095/220442096-b9554704-7144-4552-a216-e46f49636330.png)

Please note that the database only has one entry for default for type { type: 'scooldspace'}

![image](https://user-images.githubusercontent.com/59799095/220442202-d358a511-dfcd-446c-9fd0-4fe18293aede.png)

Steps to replicate:

Windows 10 Pro, Chrome Version 110.0.5481.104
1. Clone Para latest master, build, start with Mongo DB
2. Setup another app called myapp -- para-cli new-app "myapp" --name "My App"
3. Clone scoold latest master
4. Open http://localhost:8000
5. Create a new user (without OAuth). Login with this user
6. Click on Spaces. This shows two default space -- 'default' and 'Default Space' which is confusing

Possible code issue:
ScooldUtils.assignSpacesToUser --> authUser.getSpaces().addAll(assignedSpaces);
![image](https://user-images.githubusercontent.com/59799095/220446206-845baf49-2abf-475f-9374-755fdc2e2f30.png)

The problem is that authUser.getSpaces() returns a DEFAULT_SPACE and assignedSpaces also contains a default space

**Comment by albogdano** [comment]
I believe this was fixed in Scoold `1.52.1`. Please confirm you are running the latest stable version.

**Comment by ajz007** [comment]
ohh.. my bad then. I am testing in 1.52.0
I can check again on the latest version.

**Comment by ajz007** [comment]
I checked this again in the latest version 1.52.1 and I can see the same behavior
![image](https://user-images.githubusercontent.com/59799095/221355481-d4cddc88-ec05-40cb-86e7-811068240f53.png)

**Comment by albogdano** [comment]
Fixed, thanks!
