### ISSUE TITLE
There is a problem with playback when uploading a video.

### ISSUE THREAD

**Issue by 94tiger** [Erudika/scoold#371]
I am currently using version 1.52.3 and using AWS S3 as the upload server.

When I add a video to a post, there is a problem with playing the video.
When uploading a video with the file name "flower.webm", it is written in the following format.
```
!V[flower.webm](sourcelink)
```
This is again converted to the following form of source code.
```
<video title="flower.webm" controls="">
 <source src="sourcelink" type="video/webm" />
  Your browser does not support the video element.
</video>
```

I tried running this source on my other server, played normally, but it doesn't work on scoold.

I thought it was a problem only on my server, so I tried running it on the demo server, but it was the same.
https://live.scoold.com/question/1551450714662768640/markdown-test

**Comment by albogdano** [comment]
Make sure you have Scoold Pro up and running before trying to upload images or videos. I see no problem with the webm file format. As you can see, I uploaded the same video clip on the Scoold Pro demo site here: https://pro.scoold.com/question/1530871557759438848/how-to-upvote-in-scooled-platform#post-1544164902225055744

**Comment by 94tiger** [comment]
Yes, I'm currently using the Pro version.
I also checked what you posted.

When uploaded locally, it seems to play normally.
However, when I upload using AWS S3, it does not play.
When uploading an image, it comes out normally, so it is not a problem with S3 settings.

**Comment by 94tiger** [comment]
It was a CSP issue, and I solved it by using `scoold.csp_header_enabled = false` option.
However, I'm not sure what the difference is between local and AWS S3.

**Comment by albogdano** [comment]
For files uploaded to S3, Scoold will read them and serve them from the same domain where Scoold is hosted, not from the AWS S3 domain. This does not require changing the CSP settings. If you add a link to the video in Markdown to point to its S3 URL, then it won't play because the CSP does not allow content from that domain, unless you explicitly add the domain to the CSP header.

**Comment by 94tiger** [comment]
Even if I don't change the CSP settings, the image prints normally, is it different from the video?

**Comment by albogdano** [comment]
It should not matter if the file is a video or an image but I will check for any bugs...

**Comment by albogdano** [comment]
Just checked on a Scoold Pro server with S3 configured - both video and image uploads load correctly without CSP modifications.
