### ISSUE TITLE
Beginner Question : How can I split scoold.js into module files?

### ISSUE THREAD

**Issue by ja-ho** [Erudika/scoold#372]
Hi!
I am trying to split scoold.js into multiple files. Is there any specific reason  the javascript code is all in one file?
If it is possible to split the code, I would like to ask how. Is the module bundler applied to scoold? If not, can I build it by adding a module bundler? Thanks so much!

**Comment by albogdano** [comment]
Splitting the main JS file would give you a negligible performance increase and I don't see a point in doing it. Scoold does not use any module builder whatsoever. It's just plain old jQuery. Complicating the build process is strongly discouraged.
