### ISSUE TITLE
[FR]: Preset List of Tags

### ISSUE THREAD

**Issue by SHogenboom** [Erudika/scoold#373]
Would it be possible to add an option where users select tags from a predefined list? 

We want to use Scoold for a Q&A system for different university courses. The tags - which should refer to the courses - are easily misspelled. It would be ideal if we could predefine some tags for students to use when creating new questions.

**Comment by albogdano** [comment]
I can add a new configuration option allowing only admins or moderators to add new tags to questions. We have no plans to add a more complex tag management system on the Administration page in Scoold. You will be able to lock tag creation and then create a sample question with the tags you need or allow students to create the tags themselves, edit them and, when all required tags are present, lock tag creation with the new option. 
Will that work for you?
