### ISSUE TITLE
[FR]: ‘Home’ after creating a Question

### ISSUE THREAD

**Issue by SHogenboom** [Erudika/scoold#374]
We’ve had some issues with the UI/UX after creating questions. Specifically, because one is not returned to ‘All Spaces’ after creating a question, it could appear as if your question was not created if you assigned it to a different Space. We would therefore like to request the feature that one is returned to a ‘Home’ page after creating a new question.

**Comment by albogdano** [comment]
I'm not sure I understand how the current redirect behavior is confusing. The name of the space is clearly visible on top of the page, above the question title.

**Comment by albogdano** [comment]
Closing this for now because it's unlikely to be implemented.
