### ISSUE TITLE
Custom welcome message breaks Scoold for users with apostrophe in name

### ISSUE THREAD

**Issue by j3monkau** [Erudika/scoold#375]
Hi,

We are running Scoold Pro 1.52.1. 

We have experienced issues with users with apostrophes like O'Donnel in their name not being able to use the site. This happens only when using a custom welcome message. It seems like the string for the custom welcome message, where the username is injected, closes because the username string is not properly encoded. This causes all functionality that relies on Javascript to stop working. 

For every page we get this error:

![image](https://user-images.githubusercontent.com/14153508/235621397-d8c92d9c-b0de-4ccf-975a-37ee9dd693a6.png)

**Comment by albogdano** [comment]
Fixed, thanks!
