### ISSUE TITLE
Questions and answers appearing from 'Deleted User' when looking at use profile pages

### ISSUE THREAD

**Issue by asos-robbell** [Erudika/scoold#379]
When looking at a user's profile page, all of their question and answers listed under their profile appear to be from 'Deleted User'. The list of questions and answers is correct for the given user, but the icon and name appear wrong:

![image](https://github.com/Erudika/scoold/assets/62598928/d8983c35-4374-4e9c-927b-9b3e8cbf62dc)

**Comment by albogdano** [comment]
I think that was fixed a while ago... Which Scoold version do you have?

**Comment by asos-robbell** [comment]
This is with v1.53.0

**Comment by albogdano** [comment]
Fixed.

**Comment by asos-robbell** [comment]
> Fixed.
Fixed in a new version, or you mean it was fixed previously? Regarding your other comment, all of this data was created via the app and not imported. All users are seeing the same behaviour. We use OpenID auth with Azure AD, I'm not sure if that's a contributing factor?

**Comment by albogdano** [comment]
Did you experience any other issues like that elsewhere on the site? What about the description of that question in the screenshot - can you see all questions normally?

**Comment by asos-robbell** [comment]
> Did you experience any other issues like that elsewhere on the site? What about the description of that question in the screenshot - can you see all questions normally?

Every question on all users' profile pages appear with 'deleted user' consistently:

<img width="320" alt="image" src="https://github.com/Erudika/scoold/assets/62598928/1d6d311b-1426-46b4-bbe7-89098e9ef3a0">

It's the same on the answers tab, although with a smaller icon:

<img width="231" alt="image" src="https://github.com/Erudika/scoold/assets/62598928/fa7ac4d3-52d5-4fa4-a0ac-012b6bcb1291">

The profile page is the only place that I see the 'deleted user' issue—all other pages show the correct user.

**Comment by albogdano** [comment]
Ok that's fine. The issue is definitely fixed now and you should get it with the next release of Scoold Pro.
