### ISSUE TITLE
ParaObject scooldspace:default

### ISSUE THREAD

**Issue by fpellet** [Erudika/scoold#380]
Hello,

With the latest version, I have a space that has been added to all users.
I don't see what it is and I can't delete it. Deletion does nothing at all.
How can I remove it and have a default space as before?
![image](https://github.com/Erudika/scoold/assets/1950032/fa7340fd-5732-470a-b45d-7a60441629c9)
![image](https://github.com/Erudika/scoold/assets/1950032/ffd64ec5-7d75-4848-809a-57bab0d5b87f)

**Comment by albogdano** [comment]
Try renaming it to "default"

**Comment by albogdano** [comment]
You should actually edit the `scooldspace` object itself using the Para web console or `para-cli`.

**Comment by albogdano** [comment]
You can even delete the object `scooldspace:default` from Para entirely and that won't affect the normal operations in Scoold.

**Comment by fpellet** [comment]
Sorry, but the object `scooldspace:default` does not seem to exist. Moreover in the url of these two spaces, it is the same id.  
I can't rename it either.  
Can you tell me the command on `para-cli` to be sure?  
`para-cli search "*" --type scooldspace` return empty
