### ISSUE TITLE
Missing certificate parameters for providing ldaps connection

### ISSUE THREAD

**Issue by TooFeD** [Erudika/scoold#381]
I'm trying to configure ldaps connection to my server and I'm getting certificate missing failure:
`Failed to authenticate user with LDAP server: simple bind failed: ldaps.myldap.com:636; nested exception is javax.naming.CommunicationException: simple bind failed: ldaps.myldap.com:636 [Root exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]`

Here is the configs which I'm using:
```
scoold.security.ldap.bind_dn = "CN=my-ldap,OU=Systemaccounts,DC=myldap,DC=com"
scoold.security.ldap.bind_pass = "mypass"
scoold.security.ldap.base_dn = "DC=myldap,DC=com"
scoold.security.ldap.user_search_filter = "(&(objectClass=user)(sAMAccountName={1}))"
scoold.security.ldap.server_url = "ldaps://ldaps.myldap.com"
```
Do I miss something or does scoold support ldaps auth?

**Comment by TooFeD** [comment]
I forgot to add that I'm running scoold in k8s with scoold container. How to add it to container? I thought that it must be env variable or scoold parameter which will contain cert values.

**Comment by albogdano** [comment]
I really have no idea how that would be configured on K8s tbh. I will check the LDAP API if it allows configuring self-signed certs.

**Comment by albogdano** [comment]
Your only option is to add the certificate to a keystore, bind the keystore+truststore as volume to the container and then start Para with the following system properties by editing the `JAVA_OPTS` boot parameter:

```
docker run -ti -p 8080:8080 --rm -v $(pwd)/data:/para/data \
  -v $(pwd)/application.conf:/para/application.conf \
  - v keystore.jks:/para/keystore.jks  \
  - v truststore.jks:/para/truststore.jks
  -e JAVA_OPTS="-Dconfig.file=/para/application.conf -Djavax.net.ssl.keyStore=/para/keystore.jks -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStore=/para/truststore.jks -Djavax.net.ssl.trustStorePassword=password -Djavax.net.ssl.type=JKS" \
erudikaltd/para:latest_stable
```
See here for details: https://stackoverflow.com/a/70575845/108758

**Comment by TooFeD** [comment]
Providing keystore parameter into para backend did help.
