### ISSUE TITLE
voteup votedown not working properly

### ISSUE THREAD

**Issue by Saurabh48** [Erudika/scoold#384]
if one person do voteup or votedown then after few seconds another person can't do voteup or votedown

**Comment by albogdano** [comment]
Are talking about the Scoold API? Please, provide more details to reproduce the issue.

**Comment by Saurabh48** [comment]
yes i am using scoold api to voteup and votedown

**Comment by albogdano** [comment]
I am not able to reproduce this issue. Are you sure there are no error messages in Para or Scoold logs? The normal behavior is that the post becomes locked only for the person who voted not everyone.

**Comment by Saurabh48** [comment]
i am using scoold locally in my machine through docker. can you tell me where to find scoold and para logs for this issue?

**Comment by Saurabh48** [comment]
yeah i got it. the issue is solved now.
Thanks for the help
