### ISSUE TITLE
2000 approved domains 

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#389]
hi Alex

I have about 2.000 domains I want to use as approved. What is the best way to implement it?
Thank you
Radek

**Comment by albogdano** [comment]
That's quite a lot but I think it shouldn't be a problem because the configuration value will be loaded once on startup. You can add a large string in the configuration on multiple lines like this:
```
scoold.approved_domains_for_signups = """domain1.com,
domain2.com,
domain3.com"""
```

**Comment by cimenta** [comment]
wouldnt it be an issue when editing configuration?

**Comment by albogdano** [comment]
It shouldn't be an issue.

**Comment by cimenta** [comment]
- could the list of domains be uploaded as a file? csv, perhaps
- could the list be managed via API?

**Comment by albogdano** [comment]
To both questions, the answer is no.
