### ISSUE TITLE
Odd / incorrect country names on language selection page

### ISSUE THREAD

**Issue by cjsmeele** [Erudika/scoold#39]
Running Scoold v1.29.0, accessing from Firefox ESR on Linux (though that probably doesn't matter).

On the `/languages` page, the country names of some languages are incorrect (or at least unexpected):
See attached screenshot (German -> Greece, Spanish -> Peru, and possibly more - I haven't checked).

It seems related to the choice of locale names: At the translation page (e.g. at `/translate/de`), the URLs for each word / sentence contain `de_GR`, while it should probably be `de_DE` instead.

![x](https://user-images.githubusercontent.com/2670982/37662609-b65f4f96-2c57-11e8-82e9-3e3e26bf407b.png)

**Comment by albogdano** [comment]
Thanks for reporting this! I'll fix it for the next release.
