### ISSUE TITLE
not being able to set profile picture

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#390]
Hi
after setting up custom domain I am not able to set up profile picture. 

In console I can see

Content Security Policy: The page’s settings blocked the loading of a resource at data:font/ttf;base64,AAEAAAASAQAABAAgR0R… (“font-src”). 2 [radek-](https://ask.com/profile/1582393399393128448/radek-%C5%A1im%C4%8D%C3%ADk)
POST
https://ask..com/reports/cspv [HTTP/1.1 403 Forbidden 30ms]

Can you please fix?
Thank you
Radek

**Comment by albogdano** [comment]
Did updating `scoold.host_url` fix the issue?

**Comment by cimenta** [comment]
yes, it did help. 

I am still getting these errors but there are on every single page and it is not realated to the profile icon


Content Security Policy: The page’s settings blocked the loading of a resource at data:font/ttf;base64,AAEAAAASAQAABAAgR0R… (“font-src”). 2 [sourcetree-will-not-start](https://ask..com/question/1582392767554785280/sourcetree-will-not-start)
POST
https://ask..com/reports/cspv
[HTTP/1.1 403 Forbidden 30ms]

POST
https://ask..com/reports/cspv
[HTTP/1.1 403 Forbidden 31ms]

**Comment by albogdano** [comment]
Might be a caching issue - try a refresh.
