### ISSUE TITLE
post preview

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#391]
hi

when creating or editing new question or answer it would be great to see a preview the same way other users will see it once saved.

Some formatting is seeing but inserted pictures are not.

Thank you
Radek

**Comment by cimenta** [comment]
hm, I  can see that preview is actually available. Coud we set up that "Toggle Side By Side" is ON by default?

Users will not search for that option. They would complain that it is not available.
Thank you
Radek

**Comment by albogdano** [comment]
There is no option available for the editor to make that happen easily.

**Comment by albogdano** [comment]
[EasyMDE](https://github.com/Ionaru/easy-markdown-editor)
