### ISSUE TITLE
scoold.min_tags_per_post not working correctly

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#393]
Hi

I got set up

scoold.tag_creation_allowed = false 
scoold.min_tags_per_post = 2

when a user tries to create a question without tags he will get an error message. Then he enters any tags and the question is created but without tags.
 
Could you please fix?
Thank you
Radek

**Comment by cimenta** [comment]
hi Alexander
when you fix something I guess it is not available immidiatelly. So how can I know when I can test and use?
Should not it be closed after retesting?
Thank you
Radek

**Comment by albogdano** [comment]
We can reopen the issue if the problem persists. The changes will be available soon, after I publish a new version of Scoold and Scoold Pro. You can check [here](https://github.com/Erudika/scoold/releases) or [here](https://github.com/Erudika/scoold-pro/releases) for new releases. Also, there is a changelog on Scoold Cloud, next to your Scoold Pro version label.

**Comment by cimenta** [comment]
Can I subscribe to any email with release notes of Scoold Pro?

Thank you
Radek

**Comment by albogdano** [comment]
I think you can click the "Watch" button at the top of the repository, then Custom > Notify on Releases.

**Comment by albogdano** [comment]
Scoold `1.54.1` has been released.

**Comment by cimenta** [comment]
hi Alex
I cannot see any difference. Still the same behaviour.
Could you please check?
Thank you
Radek

**Comment by albogdano** [comment]
Your server on Scoold Cloud was updated to 1.54.1 recently. Try creating a new question without tags and then add the required number of tags.

**Comment by cimenta** [comment]
hi
it still does not work

![image](https://github.com/Erudika/scoold/assets/1837850/a82e0921-1d8d-46fc-8f60-77b74fc289d5)

So currently user is NOT able to save a question but the error message is misleading. See the pic. The user entered 2 tags so I am sure that user will be confused why the error. 

Please update the error message to something like "You are not allowed to create new tags, please use only existing tags"

Thank you
Radek

**Comment by albogdano** [comment]
I fixed the autocomplete to not allow tags to be added unless they exist.
