### ISSUE TITLE
Mark accepted answer as not valid

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#394]
hi
we want to use Scoold to build a knowledge base that is "always" up to date. To actually get help from our community it would be great if any user can mark accepted answer as "not valid anymore". Then admin will review and take any appropriate action.

Thank you
Radek

**Comment by albogdano** [comment]
I think this is nice to have but there is already reporting functionality in place which does the same thing. 
![Screenshot from 2023-06-28 17-42-50](https://github.com/Erudika/scoold/assets/346873/da687841-da82-4d7f-90a0-be6001fc91fb)
