### ISSUE TITLE
moderator for a space only

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#396]
Hi Alexander 

could you make is so that a modetor can moderate a space not whole site?

I want Scoold to be adopted company wide and I am offering everyone a space for their team, customers or just a project. Then of course we need a moderator for that space only. The mod could manage questions, answers and of course add and remove users from the space.

Thank you
Radek

**Comment by cimenta** [comment]
hi Alexander
I would like to extend this feature request for spaces

Could you please make these settings available per space?

- scoold.tag_creation_allowed 
- scoold.min_tags_per_post 

Thank you
Radek

**Comment by cimenta** [comment]
hi Alexander
also please add this setting for space

scoold.posts_need_approval
scoold.answers_approved_by

or even better if all of Property key & Description settings can overwrite default settings per space.

thank you
Radek

**Comment by albogdano** [comment]
> The mod could manage questions, answers and of course add and remove users from the space.

Note that this is not currently possible and will not be possible because only admins can assign people to spaces.

**Comment by cimenta** [comment]
Hi Alexander

I just want to confirm whether you can or will not implement a feature where each space can have their own mods

Thank you

Radek

**Comment by albogdano** [comment]
@cimenta This has been implemented already, a while ago. You can manage spaces per user on their profile page after you set `scoold.mods_access_all_spaces = false`

**Comment by albogdano** [comment]
You shouldn't see a single "Make mod" button if you have `scoold.mods_access_all_spaces = false`.
There should be a button for every space on the user's profile page, like this:
![Screenshot from 2024-01-05 19-01-27](https://github.com/Erudika/scoold/assets/346873/d70828ab-48c9-4df8-9bfa-b5d893e02879)
