### ISSUE TITLE
notifications - list + management

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#397]
hi Alexander

could you please implement notification inbox in UI? Something similar to current notification in settings but to be displayed in UI instead of email.  I am the admin and moderator and I am always in UI so it would be helpful to see what I need to "attend". Also it woud be great to mark the notification as read or unread (in case it was not "solved" and I need to come back to that again later)

Thank you
Radek

**Comment by albogdano** [comment]
This is now possible with the following configuration:
```ini
scoold.notifications_as_reports_enabled = true
```
