### ISSUE TITLE
New questions and answers are not available

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#398]
Hi Alexanders

newly created questions and even answers are stored but not available in search or just while browsing questions.

Could you please investigate and fix?

I did restart the server.

Thank you
Radek

**Comment by albogdano** [comment]
Fixed. The problem was with the search indexing in ParaIO.com

**Comment by cimenta** [comment]
Hi Alexander
it is the same for me. I restarted Scoold server and it did not help.
Thank you
Radek

**Comment by albogdano** [comment]
Everything should be back to normal now.
