### ISSUE TITLE
Problems with avatar

### ISSUE THREAD

**Issue by Maciaszczyk** [Erudika/scoold#40]
When I want to assign an avatar to my account I go menu profile editing (http://localhost:8000/profile) in my case. I am taking "change picture" on the default avatar. After that I am writing the address http://localhost/images/mhalas.jpg where small file (1.2kB) with my avatar. After clicking enter key there is no change with my avatar.
[ScooldLog.txt](https://github.com/Erudika/scoold/files/1833509/ScooldLog.txt)

**Comment by Maciaszczyk** [comment]
I enclosed a piece of my log of course, where I was trying to change my avatar.

**Comment by albogdano** [comment]
This is normal behavior due to the Content Security Policy (CSP). Only HTTPS URLs are allowed.

> Refused to load the image 'http://localhost/images/mhalas.jpg' because it violates the following Content Security Policy directive: "img-src 'self' https: data:".
