### ISSUE TITLE
How to upload zip file?

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#405]
Hi

we are using cloud.scoold.com and I want to upload zip file. It fails. I added these to the config

`application/x-zip-compressed,application/zip`

How can I upload zip files?

Thank you
Radek

**Comment by albogdano** [comment]
You don't need any special configuration to upload zip files. They are allowed by default. If you have a proxy server in front of Scoold, it may have restrictions on the file size of uploaded files, which can be configured.
