### ISSUE TITLE
NFR - notification for new answers

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#409]
hi Alexander

could you please add equivalent to

![image](https://github.com/Erudika/scoold/assets/1837850/490c4f9b-582d-4fda-b4c8-920d64832053)

but for new answers?

We want to make sure that all answers are reviewed and correct.

Thank you
Radek

**Comment by albogdano** [comment]
That's implemented already. Everyone on Scoold can subscribe for notifications for new answers on every question. There is a bell icon on the post.

**Comment by cimenta** [comment]
yes but requires to 

1. log in
2. find the question
3. subscribe

I am asking for feature why I am going to receive a notification by itself, without the need of me doing anything.

**Comment by albogdano** [comment]
Got it. Since this feature would only make sense for moderators and admins, the switch will only be visible to them. Does that work for you?

**Comment by cimenta** [comment]
it would work perfectly for us.

And it would go nicely if the notifications would be actually also
available in UI. I asked for the in different post. I guess now you see why
we want this.

Thank you
Radek

**Comment by albogdano** [comment]
The new checkbox will be located here: 
![Screenshot from 2023-08-22 21-32-04](https://github.com/Erudika/scoold/assets/346873/b8e1ce14-3847-446d-8976-6ceae28e89b0)

**Comment by cimenta** [comment]
Hi Alexander
the feature is going to be available only after new realease, isn't is.
thank you
Radek

**Comment by albogdano** [comment]
Yes, Scoold `1.56.0` has been released already. Scoold Cloud servers will be updated to that version very soon.
