### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by distributev** [Erudika/scoold#417]
Hello,

Using docker-compose I got scoold up and running. Scoold is a useful application and has a simple architecture.

Which are the default user/password which should be used first time when Scoold is started? The documentation can be more specific as this is the first thing which people are looking after the installation (it is also a standard practice to provide a default user/password which must be changed after the 1st login)

Another thing is that the documentation mentions both 

application.conf and scoold-application.conf (besides para-application.conf) - are these supposed to be two different configuration files or it is the same configuration with two different names in different parts of the docs?

If these are supposed to be two different configuration files what kind of configurations should go in one and what kind of configs should go in the other?

**Comment by albogdano** [comment]
I updated the README to be more clear on these topics:
- There is no default admin account or a default username and password. You need to sign up for a new account. It is a standard practice but also a bad practice in terms of security.
- The Scoold configuration file is `application.conf` which can be renamed to `scoold-application.conf` or anything else, e.g. `app.conf`. Para uses the same convention for its configuration file.
- All configuration properties are listed in the Scoold README. Para needs minimal to no configuration. The Para documentation is here: https://paraio.org/docs/#005-config

**Comment by distributev** [comment]
Hello and thank you.

The readme still mentions both application.conf and scoold-application.conf and this raised my initial query if these are two names for the same file or are two different files? I understand these is configurable but still, the readme could simply mention application.conf (or scoold-application.conf, just choose one) and eliminate any potential confusion altogether.

**Comment by albogdano** [comment]
Yes, these are the same file but named differently. In most places "application.conf" is used but when describing Docker operations, "scoold-application.conf" is used because there is also a configuration file for Para. I will again edit the text to say either one or the other to prevent confusion. Thanks for bringing this to my attention!
