### ISSUE TITLE
template for new question

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#421]
hi
could you make available a template for new question? Not placeholder but text will be inserted into new question textarea.

Basically the same like here https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&projects=&template=bug_report.md&title=

The best would be if the template

- is written in Markdown
- is different for each space

thank you
Radek

**Comment by albogdano** [comment]
This was already implemented in `1.57.0`. See #413
