### ISSUE TITLE
Errors appear everytime I do a change on scoold-application.conf

### ISSUE THREAD

**Issue by distributev** [Erudika/scoold#423]
Every-time I have the app working fine and then I do a change in scoold-application.conf and I re-start the app I get errors on the screen and on the terminal. 

Then I stop the app + empty the /data/* folder + start again and errors are gone and things are working again.

This looks like some configuration values from scoold-application.conf get out of sync with the content of the /data/* folder and errors appear because of that. Emptying the /data/* folder and starting again the app will regenerate /data/* content to be in sync with the new values in  scoold-application.conf  and everything works well.

This is what is happening? Is this the expected behavior?

**What exactly get stored inside the /data/ folder?**

**Comment by albogdano** [comment]
What errors do you see exactly? Just copy/paste the whole console output. 
There is nothing to be synced between the configuration file and the database so that makes no sense to me.

**Comment by albogdano** [comment]
Is Scoold running as part of a docker-compose command or do you start each container separately, i.e. Para first, then Scoold? 
That is not normal and indicates that either the secret key for `app:scoold` has been changed and is invalid or something worse - perhaps a bug in the auto-initialization code. I will try to reproduce it tomorrow.

**Comment by albogdano** [comment]
It could be so but on my machine I saw a message "volume removed". Anyway, the command itself is not really an issue, but you will have to upgrade Para to `1.49.1`. I'm hoping to release it tomorrow.

**Comment by albogdano** [comment]
Forgot to mention that you have to update both Scoold and Para to their latest versions for this to work. The new versions are Scoold `v1.57.2` and Para `v1.49.1` and they are now available

**Comment by distributev** [comment]
Hello, 
Thank you for your work on this project. Was the new code i.e. 1.49.1 already built and published as 

```scoold-para:
    image: erudikaltd/para:latest_stable
```
?

I say this because **_this is what I use_** in the docker-compose.yml and when I stop ```docker-compose down -v``` and start again ```docker-compose up -d``` I still get the ```Critical server error.
500 org.springframework.web.util.NestedServletException: Request processing failed; nested exception is```  on the homepage

I even did ```docker-compose pull``` before starting but the error is still coming the same as before.

Maybe I need to do ```rm -rf data/*``` one last time and from now one it will work without having to remove the data?

Was the error supposed to go away just by updating to the "latest"?

**Comment by albogdano** [comment]
Yes, the latest stable tag points to 1.49.1 but you should not expect Docker to automatically update your container image. You should pull the latest image because gou are still using the cached one. Also you must get Scoold 1.57.2 otherwise the error will not go away.

**Comment by distributev** [comment]
I thought that doing ```docker-compose up -d --build``` or ```docker-compose pull``` just before ```docker-compose up -d``` + having ```image: erudikaltd/para:latest_stable``` inside the ```docker-compose.yml``` is enough to get the "latest" app.

apparently it is not, unless I missunderstand something about how docker works.
