### ISSUE TITLE
approving questions process

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#424]
hi Alexander

1) Would it be possible NOT to use the word **approve** for two different things? Even in documentation therere is "Controls who is able to mark an answer as accepted/approved." I would be great if we can use the term "**Accepted answer**"

2) would lit be possible that creator of new question is able to see, comment and edit the question even if it is NOT approved by mod? That way we can ask them to improve the queston

Thank you
Radek

**Comment by albogdano** [comment]
I will have to move the "Uapproved" button to the filter drawer where it is described more appropriately, e.g. "Show questions without an accepted answer". 

The second point is actually possible already - you can always edit your own questions.

**Comment by cimenta** [comment]
hi Alexander

#2 is not working correctly.

Steps to replicate

1. make sure that new questions require approval
2. create new question and save
3. copy the url open new window/tab place url and load the page. You are able to see the question
4. click questions and you are not able to see the question.

Could you please fix this?

Thank you
Radek

**Comment by albogdano** [comment]
You can't see your own unapproved questions on the Questions page because they are not there as questions yet.
You can however see all your questions and answers (even if they are not approved) on your Profile page.
This is just how Scoold works at the moment.

**Comment by cimenta** [comment]
oh, ok. At least creator of a question can see it. It make sense that they would see unapproved question under Questions if only the creator can see them. It is a queston after all.

Happy to know that author can edit / delete their quesions at any time

Thank you
Radek
