### ISSUE TITLE
tags improvements

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#425]
Hi Alexander

1. Could you please make tag case sensitive? If I rename a tad but to BUT it stays but. 
2. Could you please introduce tag's description. A text description that would be vistible 
* upon mose over a tag 
* when adding new tag to a question

thank you
Radek

**Comment by albogdano** [comment]
Tags will not likely every be case sensitive.
Tag description is possible but I can't say when it will be implemented.
