### ISSUE TITLE
user search

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#429]
Hi

could you make is so search works for substring? Not only for exact match?

If I search for Rade nothing is found but I search for Radek all users with Radek name are displayed.

Thank you
Radek

**Comment by albogdano** [comment]
Not sure I can replicate this issue. The search works on substrings of the user name already. You can try it on the demo page, for example: https://live.scoold.com/search?q=ren

**Comment by albogdano** [comment]
I fixed the behavior of the smaller search bar to be consistent with the global search bar.
