### ISSUE TITLE
Themed Translations

### ISSUE THREAD

**Issue by bjoekeldude** [Erudika/scoold#43]
We want to use sccold for our [car-diagnostics forum](https://fragen.car-diagnostics.eu). Therefore we'd like to make our own translation with car-themed name-tags at buttons. should we do this locally or also make a pullrequest to you repo? Maybe it's a fun thing to see for other users and give them some creative influence?

**Comment by albogdano** [comment]
I think it's better for everyone that you just make these customizations locally. I'm willing to merge PRs which are beneficial for everyone using Scoold, but this is too specific for your needs. 
Tell me if you need help with translations. The language files for English or German are all you need you edit. Also have a look inside `macro.vm` for the snippets of code which render tags `#tagsbox` and votes `#votebox`.
