### ISSUE TITLE
new question template

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#431]
hi Alexander

it looks that each space got its own new question template. Is that a feature or fluke?

If if it is a feature would it be possible 

1. to force a user to choose space (if no space selected) when creating new question and then 
2. load the correct template?

Currently

1. template is loaded
2. user create a question 
3. at the end selects space
4. saves new question

In case the quesion is meant for different space than already selected the correct / desired template will not be presented to the user.

Desired flow when creating new question would be

1. user clicks "Ask Question" button
2. either desired space is selected or user selects desired template
3. space template is loaded
4. user finishes a question and saves

Possible solution is to introduce new configuration

-  that would load space template
-  when space is changed 
-  when creating new question

there is a question whether the template should be added to existing question body or just replace existing text.

What do you think?

Thank you
Radek

**Comment by albogdano** [comment]
Yes, I will fix that so that when you visit the "Ask question" page and change the space, the correct template is loaded.
To answer your first question - no, we cannot force a user to choose a space, but you can have a default template for the default space.
Do you need one template for all spaces?

**Comment by cimenta** [comment]
hi Alex

the current behavior = each space can have its own template = is exactly what we want. 

So if you can make it that changing space will 

- add template text in front of the existing one - preferable solution
- replace existing text with template text

then we are very happy.

Thank you

Radek
