### ISSUE TITLE
Restore data from PostgreSQL

### ISSUE THREAD

**Issue by maor-paz-hs** [Erudika/scoold#435]
Hi, 
All of a sudden, All data disappear when connecting to Scoold. 
Nothing happened to the database, 

Para installed on EC2
Scoold installed on k8s,
Database on managed RDS PostgreSQL

I created new instances, 
All of the themes running on k8s without any issues,

but I do need my data.
Do you know how I can restore it?

**Comment by albogdano** [comment]
Perhaps you just need to rebuild the search index (Search > Admin > Env > Rebuild). The data is most probably still there in RDS but do check.
The search index is stored locally on the k8s pod which may or may not have it saved permanently on disk (check if you have attached volumes for the `./data` folder)

**Comment by maor-paz-hs** [comment]
Ok, 
So i've done export and import, that didn't helped...

also done rebuild for the index, not helped, 
It does bring all the tags, but no questions.

**Comment by maor-paz-hs** [comment]
Another wired thing, 

On user's
profile, I can see answers of themes along with questions. but once I click on it, I see now questions page again. 

![image](https://github.com/Erudika/scoold/assets/146072558/3105e84f-d876-46e1-b3d0-6ad1e83b9f24)

**Comment by albogdano** [comment]
Are there any questions in the database? Use the data explorer to filter rows by `type = question`

**Comment by maor-paz-hs** [comment]
```
select *
from para_scoold ps
where ps.type = 'question' 
;
```
![image](https://github.com/Erudika/scoold/assets/146072558/76510a4e-6094-4806-bd98-51ec78fa17cd)

**Comment by albogdano** [comment]
Not sure why you stopped seeing results in Scoold while the data was still there. That's not normal behavior. 
I'm glad you were able to solve the issue! :+1:
