### ISSUE TITLE
make aproval process settings independent

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#437]
hi Alex

please make it so we can turn off approval for answers if questions needs approval. It seems to me that new option for space settings and default one will do

![image](https://github.com/Erudika/scoold/assets/1837850/5a4f8ec0-b5a0-47c1-b11c-3bf3a1f24218)

What do you think?

Thank you
Radek

**Comment by cimenta** [comment]
hi Alex
how was this implemented? By this option? 

> scoold.answers_need_approval

Enable/disable the need for approval of answers by a moderator.

Does it mean that it is only global option and cannot be different per space?

Thank you
Radek

**Comment by albogdano** [comment]
Yes, this is a global-only option for now.
