### ISSUE TITLE
adding Tags with <Return>-Key

### ISSUE THREAD

**Issue by bjoekeldude** [Erudika/scoold#44]
When asking a new question, adding tags is mandatory. This is fine I guess, but what sucks about it, is that to add a tag, one needs to klick on the droped down menu. Could this be changed in adding the first suggestion by just taking the <Return>-Key?

**Comment by albogdano** [comment]
That functionality is taken care of by a plugin called [materialize-autocomplete](https://github.com/icefox0801/materialize-autocomplete) and it's considered to be part Scoold. You can just use the down arrow (:arrow_down:) to select the first suggestion and then press ENTER.
