### ISSUE TITLE
api to create new user

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#444]
hi Alex

I want to use API to create new user. I will user https://live.scoold.com/apidocs#/users/post_api_users but there some things not clear to me.  Could you please help me with

1. understanding what fields are mandatory? Is it good enough if I specify email and name?
2. I want to assign this new use to a space. Should I use field "space"? What would be the value? Space name or ID?
3. what happens after the user gets created? Are they notified via email?
4. I want them to set up their password upon first login. I do not want to set up their password while creating the account.
5. What happens if the email domain is NOT in approved domains list when creating the user?

Thank you
Radek

**Comment by albogdano** [comment]
1. You need these fields as a minimum: `name` `email` `password` `"identifier": "email"`
2. Yes, the correct field is `spaces` and it is an array of strings like this: `["scooldspace:test-space:Test space"]`
3. Nothing - the user will not get a notification as it is currently configured
4. Possible, but only through the reset password functionality on the 'Sign in' page
5. The API call will let you create any user even if their email is not in the whitelist of domains but the user will not be able to login and will get an error

**Comment by cimenta** [comment]
hi Alex

1. something like that?
```
{

  "identifier": "email",
  "name": "firstname and lastname",
  "email": "fake@eamil.com",
  "password": "some passsrod string"
}
```
so we do not need to specify active: true?

2a. could you please explain the syntax of ["scooldspace:test-space:Test space"] ?
I guess that scooldspace is a key. What is "test-space"? What is "Test space"?
2b. do I need to specify default space? Or it is going to assigned by default? Even if there is no space specified, even if there is a space specified?

Thank you
Radek

**Comment by albogdano** [comment]
Yes, that's correct. 
No need to specify `active: true`.
All spaces have the same syntax of their IDs - 
```
scooldspace:{space_id_without_whitespace_or_symbols_only_dashes}:Space name with symbols and whitespace"
```
No need to specify the default space which has an ID `scooldspace:default`

**Comment by cimenta** [comment]
hi Alex

I get this error "Failed to create user - identifier is invalid - identifier field must be an email or start with a valid prefix," for this request data

{"identifier":"email",
"name":"testingPFXlogic testing",
"email":"testingPFXlogic@rak.com",
"password":"123",
"spaces":["scooldspace:tt-celp-12-8-2024-sst-us:Configuration Engineer Training"]
}

could you help me?

Thank you
Radek

**Comment by albogdano** [comment]
I forgot to mention that `identifier` should be the actual email and identical to the `email` field. Sorry about the confusion.
So try: 
```
{
"identifier":"testingPFXlogic@rak.com",
"name":"testingPFXlogic testing",
"email":"testingPFXlogic@rak.com",
"password":"123",
"spaces":["scooldspace:tt-celp-12-8-2024-sst-us:Configuration Engineer Training"]
}
```

**Comment by cimenta** [comment]
works perfectly...

one more question. If someone rename the space then the user will not be created?

**Comment by albogdano** [comment]
As long as the space ID matches that in the database there will be no problem. For example, if `scooldspace:tt-celp-12-8-2024-sst-us:Configuration Engineer Training` was renamed, only the last part will change and the ID will stay the same:
```
scooldspace:tt-celp-12-8-2024-sst-us
```
Also, you should be able to only specify the ID inside the `spaces` array and the request should still work:
```
"spaces": ["tt-celp-12-8-2024-sst-us"]
```

**Comment by cimenta** [comment]
that works ok but ...

If I call  the create new user API end point with the same data

1. the first call creates new user
2. all following calls return the users details

- Could you please comment on the #2? 
- Is that correct desired behavior? 
- Does such call update the password?
- How can I find out if the user was created or already existed?

**Comment by cimenta** [comment]
> 
> Also, you should be able to only specify the ID inside the `spaces` array and the request should still work:
> 
> ```
> "spaces": ["tt-celp-12-8-2024-sst-us"]
> ```

"spaces": ["tt-celp-12-8-2024-sst-us","testspace"]  did not work for me

**Comment by albogdano** [comment]
Sorry, I gave you the wrong search type - try  `GET /api/search/user/radek` or `GET /api/search/profile/radek`

**Comment by cimenta** [comment]
> Sorry, I gave you the wrong search type - try `GET /api/search/user/radek` or `GET /api/search/profile/radek`

looks like none of them lets me search for email

**Comment by albogdano** [comment]
This is the correct syntax:  `GET /api/search/user/email:"john@domain.com"`

**Comment by cimenta** [comment]
> GET /api/search/user/email:"john@domain.com"

this works. thank you

can I search for all accounts with email from @domain.com?

**Comment by albogdano** [comment]
I don't think that's possible because the `email` field is not analyzed in the search index, meaning it is either matched exactly or not at all.
