### ISSUE TITLE
Allow configuration to be saved via API on Scoold Cloud

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#445]
hi Alex 

could you please confirm my understanding on how to add new domain to approved domain list?

1. I read the whole list of approved domains as one config option via https://live.scoold.com/apidocs#/config/get_api_config_get__key_
2. I modify the list
3. save via https://live.scoold.com/apidocs#/config/put_api_config_set__key_

thank you
Radek

**Comment by albogdano** [comment]
Yes, you can modify the configuration properties from the API but changes won't be saved permanently on Scoold Cloud.
If you run Scoold locally and load the configuration from file `application.conf` then changes will be saved there in that file.

The body of the API request must be :
```
{ "value": "domain.com" }
```

**Comment by cimenta** [comment]
hi Alex

Q1: could you make is so we can modify cloud configuration via API?

Q2: can we read cloud config via API?

thank you
Radek

**Comment by albogdano** [comment]
Yes, I will work on this so that saving the configuration on Scoold Cloud servers via API works as expected.
You can read the current configuration of every Scoold server with a GET request to `/api/config`
