### ISSUE TITLE
Scoold Config Environment Variables aren't case insensitive

### ISSUE THREAD

**Issue by mljohns89** [Erudika/scoold#452]
I just realized that when setting the Scoold config via ENV variables, scoold config expects them to be in lower case.

Standard convention for ENV variables is upper case.

Looking at the code, it looks like this might be an issue for both Scoold and Para since Scoold uses the Para `Config` class:  https://github.com/Erudika/para/blob/master/para-core/src/main/java/com/erudika/para/core/utils/Config.java#L256

I tested this by trying to set a config para as an ENV variable as both `SCOOLD_PARA_SECRET_KEY` and `scoold_para_secret_key` and Scoold was only able to connect to Para when I used the lower case ENV variable.

`System.getEnv(string)` is case sensitive based on the platform the application is running on.  On Windows, it is not case sensitive.  On Linux and mac it is case sensitive.

The simplest way I can thing to fix this is by changing the above line to something like this:

```java
Optional.of(System.getenv(var10000 + "_" + key.replaceAll("\\.", "_")))
			.orElse(System.getenv(var10000.toUpperCase() + "_" + key.toUpperCase().replaceAll("\\.", "_")))
```

Let me know your thoughts

**Comment by albogdano** [comment]
Thanks for the suggestion, Michael! I changed that line in `Config.java` to first load the uppercase variable and then default to the lower case one, if it has any value at all.
