### ISSUE TITLE
Critical server error on users

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#455]
hi

I am experiencing "Critical server error." 

1. after clicking user name 
![image](https://github.com/Erudika/scoold/assets/1837850/80a9a3e6-3968-4a42-8a9c-f3a165c6b7cc)

2. searching for a user 
![image](https://github.com/Erudika/scoold/assets/1837850/cde28aa2-6b9d-4d2f-afed-f9d5cd20199e)

The error is not happening to all users.
```

Critical server error.
500 Handler processing failed: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public abstract int java.util.Collection.size() without it being registered for runtime reflection. Add public abstract int java.util.Collection.size() to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help. 
```

Could you please fix this as we are not able to make user a mod?

Thank you 
Radek

**Comment by albogdano** [comment]
Fixed, but please confirm.
