### ISSUE TITLE
default space per user

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#461]
hi Alex

could you please introduce new user setting? Default space that is selected after a user logs in. We want to use Scoold for a "private" group of users that are not that technical. It might be confusing for them to see all "default" questions. It would much better if we can have this new setting that we would set when creating the user.

Thank you
Radek

**Comment by albogdano** [comment]
Hi Radek, there is `scoold.auto_assign_spaces` specifically for for this purpose. Apart from that, you can assign spaces from OAuth2 claims where you can be configure the name of the claim where spaces are stored.
Do you have something else in mind?

**Comment by cimenta** [comment]
I am not taking about assigning a space but having specific space to be selected from drop down menu "Spaces" after a user logs in.

**Comment by albogdano** [comment]
Oh, you mean the first space a user visits after they log in? I will have to think about how this can be implemented easily. So for example a new user can be a member of spaces "default" and "custom" but when they log in, you want them to see the "custom" space first, correct?

**Comment by cimenta** [comment]
yes, that is what I am asking for.

- a user level setting 
- so user can select from all assigned spaced the one that is going to be "selected" after login
- this can be set up via API too

Thank you
Radek

**Comment by albogdano** [comment]
On each profile object there is a new property/field `preferredSpace` which can be edited from the API. Also there is a new configuration property for setting the preferred starting space globally with `scoold.default_starting_space`
