### ISSUE TITLE
Writing longer answers

### ISSUE THREAD

**Issue by bjoekeldude** [Erudika/scoold#49]
When it takes me longer to write an answer, I can still press the post button, but instead of my answer it shows a minipage of the current site.
Looks like the session expired or smth. Can one make this time longer?

**Comment by albogdano** [comment]
Has this happened once or does it happen often? It is possible that the session had expired. The session lifetime is controlled by the `para.session_timeout` property and defaults to `24 * 60 * 60` 1 day.
