### ISSUE TITLE
Feature Request: LDAP integration

### ISSUE THREAD

**Issue by duzunov** [Erudika/scoold#5]
Hello Guys, 

Scoold looks great! Do you think it is useful to integrate with LDAP or Active Directory? I think it is a must if it is going to be used by most organizations (the popularity of G Suite notwithstanding). I also don't think there are many Question CMSes that have this feature.

Best regards!

**Comment by albogdano** [comment]
Hi,
That would be a great feature but unfortunately I have no experience with the LDAP protocol and this will take some time. Scoold is mostly frontend code - the new LDAP integration code would belong to [Para](https://github.com/Erudika/para) which is the backend behind Scoold. 
I would be happy to review any ideas or code for such an integration.

**Comment by albogdano** [comment]
@duzunov LDAP support is implemented in Para now, scheduled to be published on Maven very soon. After this, Scoold will automatically support LDAP. I just have to do some frontend work to display the LDAP login form.
