### ISSUE TITLE
How could I get the database model?

### ISSUE THREAD

**Issue by furaul** [Erudika/scoold#50]
Hello everyone , 
I've been researching scoold for several days, what I've got is that scoold is a web site that contains frontpages and controllers only. And scoold get the datas from para service through http calls. So, how could I get the whole scoold database model?

**Comment by albogdano** [comment]
Scoold has no DB schema because Para is schemaless. It was designed for NoSQL storage. All the data is stored in a single table in DynamoDB.

**Comment by furaul** [comment]
I've been build a para and scoold in my PC, and I create some questions. So, how could i get data records in para or DynamoDB?

**Comment by albogdano** [comment]
Please read the documentation at https://paraio.org/docs
