### ISSUE TITLE
Running scoold with para running locally?

### ISSUE THREAD

**Issue by ramswaroop** [Erudika/scoold#52]
Hi, I want to run scoold with para running on the same machine. So, what I need to do is:

1. Clone/get the latest war from para github.
2. Edit the application.conf file for para and run para.
3. Make scoold use the para running on the same machine.

Is this the right way? Is there any way to make para run within scoold itself so that I don't have to worry about running/starting para?

And also, do I have to setup/install any database for para to run or is it taken care automatically by para?

**Comment by albogdano** [comment]
That's the correct procedure, yes. You need 2 config files for Para and Scoold. Para can't be embedded in Scoold, at least not easily. You could just create a simple run script to execute one before the other.
By default Para will save data to H2 DB, so no need to install anything.

**Comment by ramswaroop** [comment]
Will close the issue after setting up scoold and para. Probably tomorrow.
