### ISSUE TITLE
Dockerfile / hub.docker.com release ?

### ISSUE THREAD

**Issue by jkroepke** [Erudika/scoold#57]
Hi,

do you plan to create a Dockerfile or a hub.docker.com release?

**Comment by albogdano** [comment]
Yes, I've been planning to do this for some time. There are 2 options here - a standalone Scoold dockerfile and a combined Scoold+Para dockerfile.

**Comment by jkroepke** [comment]
I would prefer a standalone container, since one container - one process.
In addition a docker-compose for a example prod environment would be awesome. (Maybe with ES and Mongo)

Today I tried to deploy it in our Kubernetes/Openshift Cluster, but I can't get it.

**Comment by albogdano** [comment]
Scoold is now released on Docker Hub: `docker run -it erudikaltd/scoold:1.29.3`
