### ISSUE TITLE
Unexpected behaviour in e-mail log-in with unregistered address

### ISSUE THREAD

**Issue by cjsmeele** [Erudika/scoold#59]
Hi! I ran into a confusing issue with e-mail auth:

This happens when a user attempts to log in with an unregistered e-mail address (e.g. when making a typo or by forgetting that they hadn't made an account yet):

**if e-mail verification is enabled**
A verification mail is automatically sent to that address, as if the user was trying to register.
Clicking the verify link creates a new user with the confusing name "ParaObject N" where N is some large ID number.

**if e-mail verification is disabled**
A new user with a "ParaObject N" name is immediately created and logged in.

In both cases I expected the log-in to simply fail, and that new accounts can only be created on the "register" page.

Thanks for everything so far!

**Comment by albogdano** [comment]
This is because Para doesn't have a "signUp()" method, only `signIn()` so user objects are created automatically on sign in. You can restrict the domains from which users are allowed to register via `para.approved_domains_for_signups = "domain1.com,domain2.com"`
