### ISSUE TITLE
How to register a new user to ask?

### ISSUE THREAD

**Issue by lidongbo** [Erudika/scoold#6]
i can not find the administrator console enter point.

**Comment by lidongbo** [comment]
it dose work for me.

my `application.conf` 's content as blow

```property
para.app_name = "xxxTech"
para.port = 8080
para.env = "development"
para.host_url = "https://live.scoold.com"
para.endpoint = "http://localhost:8080"
para.access_key = "app:xxxtech"
para.secret_key = "XXX=="
para.gmaps_api_key = "********************************"
para.admin_ident = "admin"
para.support_email = "admin@google.com"
para.google_analytics_id = "UA-XXXXXX-X"
para.code_highlighting_enabled = true
```

and i get the no input for login as below screen 

![image](https://user-images.githubusercontent.com/1622374/28358485-9e356868-6ca1-11e7-95d1-66b448d8c1ee.png)

**Comment by albogdano** [comment]
First of all `para.admin_ident` should look like `gp:your_google_id` and not be equal to `admin@google.com` if you are using Google to sign in. Click on the "Show" button in the top right of the Console to see what your `identifier` is. Then save it in `application.conf`, reset your data and login again.

**Comment by lidongbo** [comment]
I changed the `para.admin_ident` 's  value to `gp:my_real_google_id`, but it still no account input area or `CONTINUE WITH XXX` option.

**Comment by albogdano** [comment]
You have to delete your user object from the database and login again. The `admins` group is set only when the user is created.

**Comment by albogdano** [comment]
Oh, you haven't configured your OAuth credentials for social login in `application.conf`:
```
# Facebook
para.fb_app_id = "123456789"
# Google
para.google_client_id = "123-abcd.apps.googleusercontent.com"
```
Read https://github.com/Erudika/scoold#social-login

**Comment by lidongbo** [comment]
I removed all of the `para\data\para-dev\nodes` files, and it still not work.  BTW ,  Does the `Scoold` must  depend on social-login ?

**Comment by albogdano** [comment]
You have to login with one of the identity providers that are currently supported - Facebook, Google, Microsoft, etc. You have to create a new developer application with each and every one of these if you want to use them for authentication in Scoold. For example, you need to create a Facebook app on https://developers.facebook.com and set the `pafa.fb_app_id` in `application.conf`.

**Comment by lidongbo** [comment]
Okey, Thank you very much, i'll try it later.

**Comment by slemkemeier** [comment]
I'm struggling with the social logins as well. I have configured both Facebook and Google apps but neither are working successfully. When I attempt to log in with one of them, there is a redirect to the signin page with the message "Authentication failed or was canceled." With Google, nothing shows up in the console, but with Facebook, this appears: "[ERROR] Failed to authenticate user with 'facebook'. Check if user is active. - HTTP 400 Bad Request". Any ideas?

Thanks so much for your help on this, it is hugely appreciated!!

**Comment by albogdano** [comment]
@slemkemeier You have misconfigured something. Make sure that you have these in your `application.conf`:
```
# Facebook - create your own Facebook app first!
para.fb_app_id = "123456789"
# Google - create your own Google app first!
para.google_client_id = "123-abcd.apps.googleusercontent.com"
```
Also the allowed domain in Facebook/Google dev console must match the domain you're trying to login from.

**Comment by slemkemeier** [comment]
I have both of those configured in my conf file. And the first step of the process is working: when I try to sign in with google I get this result:

![screen shot 2017-12-03 at 10 39 00 am](https://user-images.githubusercontent.com/9854612/33526943-3ca2a03a-d816-11e7-90c7-2d12d3b4ee59.png)

But when I sign in through google, I am then redirected to the signin page with the authentication error.

I have added the localhost to the Authorized JavaScript origins and Authorized redirect URIs (before this was configured, there was a "redirect_uri_mismatch" error that no longer appears.

**Comment by albogdano** [comment]
@slemkemeier I can't determine the cause of this issue from the limited information you have given. What is the name of your Para app?

**Comment by slemkemeier** [comment]
My para app is called scoold-demo. I am hosting it locally. And here are the lines from my config file:

# Facebook - create your own Facebook app first!
para.fb_app_id = "##########"
# Google - create your own Google app first!
para.google_client_id = "########-#######.apps.googleusercontent.com"

**Comment by albogdano** [comment]
Is this your root app or is it a child app of the root app ("app:para"). If this is the only app in the database and is the root app, do you have `para.clients_can_access_root_app = true` in your Para config?

**Comment by slemkemeier** [comment]
I'm pretty sure mine is the root - I followed the readme instructions to create a para app, so it shouldn't be a child. I added that line to the config file but still no change: when I enter my google credentials, I am redirected to the authentication error and get this in the console: "Failed to authenticate user with 'google'. Check if user is active. - HTTP 400 Bad Request"

**Comment by albogdano** [comment]
Please, paste your the config files for both Para and Scoold here, replacing secrets with "***".

**Comment by slemkemeier** [comment]
Oh - that might be my problem. Do I need a Para config file if I created the app at paraio.com (instead of downloading para)? The para docs seemed to say the config was for running Para locally...

**Comment by albogdano** [comment]
I thought you said you were running Para locally. Just paste your Scoold config then.

**Comment by albogdano** [comment]
@slemkemeier Make sure that you have a user object in the database and it has a field `active: true`.

**Comment by slemkemeier** [comment]
Manually changing one of the user objects to active worked! Thanks so much!
