### ISSUE TITLE
Issue getting google social login to work

### ISSUE THREAD

**Issue by jake4679** [Erudika/scoold#60]
I used the deploy to Heroku button, created a new Google client, etc.  However when I try to signing in using google I get the error "Authorization failed or was cancelled".  There's an error code 3 in the final URL.  Tried adding the heroku default domain to the allowed redirects on the Google API.

**Comment by albogdano** [comment]
Hi Jake, please have a look at Issue #33 first.

**Comment by jake4679** [comment]
That fixed it!  Thanks!
