### ISSUE TITLE
Multiple user accounts with the same email

### ISSUE THREAD

**Issue by rampatra** [Erudika/scoold#63]
I am facing a weird issue where there are multiple user accounts with the same email address. The old user got deleted automatically and the new user got created with the same name and email but with a score 0. And I am currently using H2DB in para.

Any ideas why this would be happening?

**Comment by albogdano** [comment]
I don't know how this could happen. What do you mean by "deleted automatically"?

**Comment by ramswaroop** [comment]
Sorry, I forgot to mention that this happened when using Google Sign In. When I signed in via google after, my previous user created from the same google account got deleted and a new user got created.

**Comment by albogdano** [comment]
I can't reproduce it. There are no duplicate emails in the DB for the demo site.
