### ISSUE TITLE
Is there any document to setup with docker?

### ISSUE THREAD

**Issue by ensecoz** [Erudika/scoold#65]
Hi,

I would like to setup scoold in the docker. Is there any guide line or document?

Thanks,

**Comment by albogdano** [comment]
I haven't written it yet. The dockerfile was just added a couple of days ago and is not yet published officially. I'm hoping to get it published today or tomorrow.

**Comment by albogdano** [comment]
Scoold is now released on Docker Hub: `docker run -it erudikaltd/scoold:1.29.3`
