### ISSUE TITLE
Allow normal user to select space to filter the questions

### ISSUE THREAD

**Issue by ensecoz** [Erudika/scoold#68]
The space concept is very good but look like only admin can see the spaces filtering

![image](https://user-images.githubusercontent.com/218494/40968545-019504fa-68e0-11e8-86dd-1af8564a5f93.png)

Is there any way to config scoold to display for everyone?

**Comment by albogdano** [comment]
Only admins can add users to spaces on the "Users" page. After you were added to one or more spaces by the admin, you should see the menu appear, allowing you to choose the current space. If you want the default space to be public, or want to have only the default space, set `para.is_default_space_public = true`

**Comment by ensecoz** [comment]
okay. I just notice that the way to edit the space is to click bulk edit spaces.

Is there any easy way to add users to all spaces automatically when user register for the first time.
And also add all users to new space (if create new one).

or may be make all spaces public so everybody can access.

Thanks

**Comment by albogdano** [comment]
There's no way to do that at the moment, unfortunately. Users have to be added manually. The whole idea of spaces was to hide some of the content for a group of users. There's no point in making all spaces public - this is what tags are for.
