### ISSUE TITLE
Cannot sign out when hosting with https

### ISSUE THREAD

**Issue by ensecoz** [Erudika/scoold#69]
There are 3 docker containers and host at https://example.local:
- reverseproxy-server (HTTPS)
- scoold-server (HTTP)
- para-server

I setup reverseproxy to redirect from HTTP to HTTPS and setup SSL properly.
Everything is working fine except when I sign out. I got this error message.

`Refused to connect to 'http://example.local/signin?code=5&success=true' because it violates the following Content Security Policy directive: "connect-src 'self' example.local www.google-analytics.com".`

`XHR failed loading: GET "http://example.local/signin?code=5&success=true".`

`XHR failed loading: POST "https://example.local/signout".`

`Mixed Content: The page at 'https://example.local/questions' was loaded over HTTPS, but requested an insecure Content Security Policy reporting endpoint 'http://example.local/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by albogdano** [comment]
http://example.local is incorrect in this case and should not be used anywhere. Have you set `para.host_url = "https://example.local"` for Scoold?

**Comment by ensecoz** [comment]
yes. already set. it look like after redirect it try to access http:// but i've checked out the source code which use relative path for redirection. i'm not sure what is happening.

[application.conf of Scoold]
`para.host_url = https://example.local`

**Comment by ensecoz** [comment]
we need to add more config to nginx in the example.

I create PR to update the doc here https://github.com/Erudika/scoold/pull/70
