### ISSUE TITLE
Support paste image from clipboard and image uploading

### ISSUE THREAD

**Issue by ensecoz** [Erudika/scoold#75]
Image is essential for Question and Answer. It would be really good to support this feature.

scoold is using simplemde. and here is the similar feature request for simplemde: https://github.com/sparksuite/simplemde-markdown-editor/issues/328

**Comment by albogdano** [comment]
Yes, it would be nice, but it's low priority for now.

**Comment by ensecoz** [comment]
@albogdano I create https://github.com/ensecoz/scoold/tree/image-upload to upload to S3 compatible api. I don't think it generic enough to be merged for now. but can be an sample. check out PR here https://github.com/Erudika/scoold/pull/82

TODO:
- we should load the implementation from the lib (not embedded)
- load js lib for upload image when  we have conf.storage

**Comment by albogdano** [comment]
There's no plan to add any new features to the open source version of Scoold. This will probably be included as a premium feature in Scoold PRO.

**Comment by albogdano** [comment]
This is now implemented in Scoold PRO.
