### ISSUE TITLE
Redirect URI mismatch for github login

### ISSUE THREAD

**Issue by mkc450** [Erudika/scoold#76]
I got the following error when I tried to use github as login service.

_error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=1529065342148_

From this (https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/) I can understand that there was redirect mismatch error. I kept the authorization callback url same as para.host_url. Help me fixing this issue.

And also I tried using google as a login service. I got the following error.

_Application failed or cancelled_. And url parameter as _code=3&error=true_

Do let me know if I am doing anything wrong.

**Comment by albogdano** [comment]
Well, the error message gives you a good explanation of what is wrong - **The `redirect_uri` MUST match the registered callback URL for this application**
Go back to your OAuth settings on GitHub and modify the redirect callback URL to match your site.

**Comment by chaitanyawolfe** [comment]
Thanks for the response.

Redirect callback URL matches my site. But still I face the same issue.The following is the URL which is requested by scoold on clicking authenticating using github.

https://github.com/login/oauth/authorize?response_type=code&client_id=ef67328725672d91e1ab&scope=user%3Aemail&state=1529394625396&redirect_uri=http://localhost:8080/github_auth?appid=para

I am running both para and the scoold locally.  para runs at port 8080 and scoold at 8000. But what I don't understand is the redirect_uri is being referred to http://localhost:8080/github_auth?appid=para .

Am I missing here something.

**Comment by albogdano** [comment]
First of all, Scoold shouldn't be using the root app 'para', instead it should have its own app 'scoold'. Second, the redirect URL should look like this (only if running locally!):
![image](https://user-images.githubusercontent.com/346873/41584396-d519063a-73af-11e8-9e6b-5afa19e340ab.png)
