### ISSUE TITLE
Users can't subscribe to their questions

### ISSUE THREAD

**Issue by fathzer** [Erudika/scoold#8]
Not sure it's a bug or a feature (I do not like): When a user browse to a question he asked, the "Send new responses on this thread to my email" is invisible. Its a good thing if user checked  "Send my an email notification when someone replies to my posts" ... but when this box is not checked, the "Send new responses on this thread to my email" is invisible too.
Tested on scoold 1.25.4.

**Comment by albogdano** [comment]
Hi @fathzer, not quite a bug but, you're right - it is a bit counter-intuitive. Working on a fix now...
