### ISSUE TITLE
LDAP credentials printing in log files

### ISSUE THREAD

**Issue by keyanwb** [Erudika/scoold#84]
Hi,
  I have noticed that the entered LDAP credentials are printed in log files during login. How to reduce the log level to Error in conf file ?

**Comment by albogdano** [comment]
Try the system property `logging.level.org.springframework.ldap=ERROR`.

**Comment by keyanwb** [comment]
Will try the same and get back to you

**Comment by albogdano** [comment]
That is a Spring Boot configuration property and should not be in `application.conf`, but `-Dlogging.level.org.springframework.ldap=ERROR` should work.

**Comment by nboughton** [comment]
I tried adding -Dlogging.level.org.springframework.ldap=ERROR to the startup line for both para and scoold and the scoold log still contains user passwords when attempting to log into LDAP.

**Comment by albogdano** [comment]
Thanks for clarifying this @nboughton! Initially, I thought this was related to LDAP but actually, it's not. Scoold's logging level is set to DEBUG by default. I'll change it to INFO. See [application.properties](https://github.com/Erudika/scoold/blob/master/src/main/resources/application.properties)
