### ISSUE TITLE
unable to find resource

### ISSUE THREAD

**Issue by AFulgens** [Erudika/scoold#85]
Probably a [PEBKAC ](https://en.wikipedia.org/wiki/User_error), but if I run the `erudikaltd/scoold` docker image with a simple `application.conf`, when I navigate to the Sign In page I get the following error:
```
2018-07-18 06:19:31 [ERROR] ResourceManager : unable to find resource 'base.json.vm' in any resource loader.
```
Thus I cannot sign up / log in to Scoold hosted in the docker image.

Any pointers are welcome.

**Comment by albogdano** [comment]
I'm not sure what's causing this issue. There's no such file. The correct filename is `base.vm`

**Comment by albogdano** [comment]
Is this issue still relevant? I will reopen it if necessary.
