### ISSUE TITLE
dockerfile improvements

### ISSUE THREAD

**Issue by weisjohn** [Erudika/scoold#88]
Opening this issue for the sake of discussion:

It seems strange to re-clone the repository when it's already locally available. Especially given the desire to build the docker container and verify it before pushing externally.

Thoughts?  If we could use `COPY`, we could allow for much quicker Docker rebuilds and tests.

**Comment by albogdano** [comment]
I'm open to `Dockerfile` modifications but I think we should clone anyway because it's meant to run on Docker Cloud's auto-build system. So basically, Docker Cloud would fetch the Dockerfile build it from scratch and release a new tag automatically.

**Comment by weisjohn** [comment]
@albogdano thanks for the education!  I'm new to docker, and though I knew about the auto-builds, I didn't understand how they worked. In this case, it would make sense to have a separate local dev Dockerfile.  If I get the chance, I'll submit one.
