### ISSUE TITLE
Can't remove moderator status to a user

### ISSUE THREAD

**Issue by fathzer** [Erudika/scoold#9]
Once a user is promoted "moderator", there's a button "Unmake mod" on its profile (see picture below).
When you click on it this button switches briefly to "Make mod" ... and switches again to "Unmake mod". Finally, the user remains moderator.
Tested on scoold 1.25.4.
![image](https://user-images.githubusercontent.com/1562721/30753875-f12fcd54-9fc0-11e7-907e-037abeeb517f.png)

**Comment by albogdano** [comment]
Yes, that would be a bug. Thanks!
