### ISSUE TITLE
Invalid cookie header

### ISSUE THREAD

**Issue by giuliocalzolari** [Erudika/scoold#90]
for some reason I received this error when I try to login using github federation.

`
2018-08-07 16:50:55,754 [WARN ] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Tue, 07 Aug 2018 15:50:55 -0000". Invalid 'expires' attribute: Tue, 07 Aug 2018 15:50:55 -0000
`

the local user and password authentication work perfectly!
do you know why?

**Comment by albogdano** [comment]
Probably the account is locked, i.e. `active: false` because the email isn't verified.

**Comment by giuliocalzolari** [comment]
I'm trying to login with the github authentication, as far as I understand no email verification are involved in this process. am I right?

**Comment by albogdano** [comment]
Yeah, I got confuse because you mentioned password auth... This seems to be related to a bug in Apache's HTTPClient. It's very strange because GitHub login was working fine up until now.

**Comment by albogdano** [comment]
@giuliocalzolari Thank you for reporting this issue! This should now be fixed.
