### ISSUE TITLE
Critical Server Error

### ISSUE THREAD

**Issue by bh679** [Erudika/scoold#91]
Critical Server Error

error 500 org.springframework.web.util.nestedservletexception: Request processing failed, nested exception is javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

![image](https://user-images.githubusercontent.com/2542558/43876860-0cbf4dc2-9bc1-11e8-83e3-c3eee30edbf0.png)

Hosted on heroku
https://forums.equalreality.com/

What do I do?

**Comment by albogdano** [comment]
ParaIO.com has been upgraded to use TLSv1.2 so you'll have to update your Para client. It's included in the latest version of Scoold `1.30.1`.

**Comment by bh679** [comment]
Thank you for the speedy response. How do I do this?

**Comment by albogdano** [comment]
You can either click the "Deploy to Heroku" button again and copy/paste your settings or clone this repository and do a `git push heroku master` from your clone. Here's the Heroku guide on this:
![image](https://user-images.githubusercontent.com/346873/43894192-051a6138-9bda-11e8-9055-4127377b3283.png)

**Comment by bh679** [comment]
Okay, I have done this. It has not worked yet.

Because I replace "scoold" with your Heroku dyno ID. Does that mean I just pulled down my current code, and than uploaded it again without the scood update?

![updating scoold-1](https://user-images.githubusercontent.com/2542558/43896259-6ea0a040-9c02-11e8-826f-5ac12df36d7e.JPG)

![updating scoold-](https://user-images.githubusercontent.com/2542558/43896265-71aed6bc-9c02-11e8-947d-7cf65b527320.JPG)

![updating scoold](https://user-images.githubusercontent.com/2542558/43896268-733b54b0-9c02-11e8-839e-3c6f0085628b.JPG)

**Comment by bh679** [comment]
Looking at the version number form the building output, it has built 1.29.3.

How do I implement the update?

**Comment by bh679** [comment]
I have also been customizing the templates. Can I keep those?

**Comment by albogdano** [comment]
Oh, yea you've just pulled your own copy which should be updated to master. I think you could add Scoold master as another remote with 
```
git remote add origin https://github.com/Erudika/scoold.git
git pull -r origin master
```
and then fix the merge conflicts (if any). Finally do a `git push heroku master` to upgrade your deployment. 
You can keep all your changes to the templates and extra files you've created but you'll probably have to manually fix any merge conflicts with a diff tool like Meld (Linux, Windows) , FileMerge (Mac).

**Comment by bh679** [comment]
For some reason I am really struggling with this.

I tried downloading the zip from the latest source, and just copy/pasting/replacing all the files in my git project, than add/commit/push. Still hasn't seemed to have worked.

**Comment by bh679** [comment]
I believe I have successfully pushed the 1.30.2 code, with my old templates to [forums.equalreality.com](url). It does not seemed to have helped.

**Comment by albogdano** [comment]
When you pull from master you have to fix the merge conflicts and then merge the remote changes from 1.30.2 into your own code and then you push to Heroku. One thing to check is the `pom.xml` file - it should contain a reference to `para-client` v1.30.2.

**Comment by bh679** [comment]
`pom.xml` looks good

![image](https://user-images.githubusercontent.com/2542558/43948040-e761fcac-9cb3-11e8-8a6d-7fcca20e180f.png)

Rather than worry about managing merge conflicts, I just copy pasted all the files from the lasted source code I downloaded as a zip than did a commit/push to heroku master.

**Comment by albogdano** [comment]
I wasn't talking about the Scoold version, rather the `para-client` version in `pom.xml` - it's declared further down the file. Also check the Heroku logs that it's actually running v1.30.2 on startup.

**Comment by bh679** [comment]
Okay, having a look at Heroku log helped me identify I was not succeeding in the push.

Problem has been solved. Thank you very much for support!

**Comment by albogdano** [comment]
I'm glad to hear that! You're welcome!
