### ISSUE TITLE
Invalid arrangement of users by reputation

### ISSUE THREAD

**Issue by bokherus** [Erudika/scoold#92]
I'm using **para 1.29.2** with **Lucene-search** and **SqlDAO.**
<img width="641" alt="bug_screenshot" src="https://user-images.githubusercontent.com/9125776/44081207-62acf624-9fd8-11e8-9b38-f7eb33b12569.png">
The reputation appears to be sorted by string. I think it has something to do with indexing from lucene-search.

**Comment by albogdano** [comment]
Thanks for reporting this @bokherus. I'll be able to fix this next week, probably.

**Comment by albogdano** [comment]
Fixed. You'll have to do a full reindex on the root app `para` (this triggers reindexing for all child apps as well). In 1.30.2 the numeric fields are no longer indexed as strings but as numbers.
