### ISSUE TITLE
Generic OAuth2 sign-in

### ISSUE THREAD

**Issue by wleev** [Erudika/scoold#93]
Is there a specific reason why this feature is absent, since it seems fully supported by Para?

What would the steps be to add this to Scoold? 
I'm thinking something along the lines of:
- Add button to `signin.vm` and click event with authorize and redirect to `oauth2_auth`
- Read custom flag in application.conf with `SigninController.java` to set `oauth2Enabled` flag
- Make sure OAuth2 Configuration is set-up in Para config

Am I missing anything?

**Comment by albogdano** [comment]
I'll try to add this in the next couple of days.

**Comment by albogdano** [comment]
This will work with the next release of Para because I had to fix a few things on the server side.

**Comment by wleev** [comment]
Thanks, when is the next release scheduled?

**Comment by albogdano** [comment]
It will be release early next week. I have to do some testing first.

**Comment by wleev** [comment]
Okido, if there's anything I can help with please feel free to let me know.

**Comment by albogdano** [comment]
Para 1.30.2 and Scoold 1.30.4 have been released.
