### ISSUE TITLE
Sending feedback requires tags, but there is no visual indication

### ISSUE THREAD

**Issue by rillig** [Erudika/scoold#97]
http://localhost:8000/feedback/write

When I enter something in the Title and Message fields and click on Go (without entering anything in the Tags field), I get redirected to http://localhost:8000/feedback, with no indication that my feedback has not been submitted.

Then, when I click on WRITE again, the Title and Message are still there, which is good. Nevertheless, something feels wrong here.

The UI should behave exactly as when asking a question at http://localhost:8000/questions/ask, where the tags are required and there is immediate input validation.

**Comment by albogdano** [comment]
Yeah, some bugs are just that simple, others can take days to fix :smile_cat: Thanks for reporting this!
