### ISSUE TITLE
Scoold GitHub Login Not Working

### ISSUE THREAD

**Issue by jmakanjuola** [Erudika/scoold#98]
Hi Alex,

So far the Scoold Project is setup and it's runninng locally. I have define para key/values in scoold/application.conf inside my running Kubernetes cluster.

I can connect my running Scoold application to https://paraio.com

For example,
`para.security_signout_success: /signin`
`para.security_signin_failure: /signin`

Another example, in an attempt to use Github to authenticate into Scoold locally, inside of Github, I created an OAuth Client ID and Client Secret and assigned the Client ID & Client Secret values to `para.gh_app_id` & `para.gh_secret` as suggested in your documentation.

`para.gh_app_id: GitHub Client ID `
`para.gh_secret: GitHub Client Secret `

Both files are defined inside Scoold config file for application.conf
when I refresh Scoold nothing no changes, the Scoold signin remains unchanged.

Could this be a bug?

**Comment by albogdano** [comment]
What do you mean it's not working? You'll have to be more specific than that. Is the login button hidden? Do you see the login button but when you click it you get an error?

**Comment by jmakanjuola** [comment]
Hi @albogdano, 
Below the Scoold screenshot. I've followed the docs around setting up GitHub Authentication 

Para key/values in scoold/application.conf

para.security_signout_success: /signin
para.security_signin_failure: /signin

 GitHub OAuth
para.gh_app_id: GitHub Client ID 
para.gh_secret: GitHub Client Secret


<img width="1114" alt="screen shot 2018-11-05 at 10 08 44 am" src="https://user-images.githubusercontent.com/4924635/48017351-f1471b80-e0e2-11e8-8524-8e558bad8936.png">

**Comment by albogdano** [comment]
Check the location of `application.conf` and make sure it's on the classpath and visible to Scoold. You're probably not setting the flag `-Dconfig.file=scoold/application.conf` so your config is not loaded at all.

**Comment by jmakanjuola** [comment]
Hi @albogdano, 

Below is the outputs of scoold/application.conf file running in my cluster. Note that I've `<xxxxxxxx>` out sensitive information.

```$ ▶ kubectl exec -it scoold-66df744d46-8sqsh /bin/sh -n scoold
/scoold $ cd /etc/scoold
/etc/scoold $ more application.conf 
para.app_name: scoold
para.port: 8000
para.env: development
para.mail.tls: true
para.gh_app_id: <xxxxxxxx>
para.gh_secret: <xxxxxxxx>
para.host_url: http://scoold.care:8000
para.endpoint: https://paraio.com
para.admins: <xxxxxxxx>
para.access_key: app:127-0-0-0-8000
para.secret_key: <xxxxxxx>
para.gmaps_api_key: <xxxxxxx>
para.security.signin: /
para.security.signout_success: /signin
para.security.signin_failure: /signin
para.password_auth_enabled: false
para.code_highlighting_enabled: true # syntax highlighting in posts
para.new_users_can_comment: true
para.is_default_space_public: true
para.security.allow_unverified_emails: false```

**Comment by jmakanjuola** [comment]
Do I need to have both Scoold and Para cluster running in parallel with one another for Github login feature to work properly in Scoold? Or can I just run Scoold as a standalone and use [](https://paraio.com) as the backend frame instead?

**Comment by albogdano** [comment]
There's no need to run a Para server if you're connecting to ParaIO.com. You only have to run Scoold but check your setup because the config file is not loaded at all probably. Do you see a warning in the logs like "No connection to Para backend"? If so then the config is definitely not loaded.

**Comment by jmakanjuola** [comment]
``` ▶ kubectl get po -n scoold
NAME                      READY   STATUS    RESTARTS   AGE
scoold-66df744d46-xljpg   1/1     Running   0          18h
└─ $ ▶ kubectl exec -it scoold-66df744d46-xljpg /bin/sh -n scoold
/scoold $ more /etc/scoold/application.conf 
para.app_name: scoold
para.port: 8000
para.env: development
para.mail.tls: true
para.gh_app_id: <xxxxxxx>
para.gh_secret: <xxxxxxx>
para.host_url: http://scoold.volvo.care:8000
para.endpoint: https://paraio.com
para.admins: <xxxxxxxx>
para.access_key: app:127-0-0-0-8000
para.secret_key: <xxxxxxx>
para.gmaps_api_key: <xxxxxxx>
para.security.signin: /
para.security.signout_success: /signin
para.security.signin_failure: /signin
para.password_auth_enabled: false
para.code_highlighting_enabled: true # syntax highlighting in posts
para.new_users_can_comment: true
para.is_default_space_public: true
para.security.allow_unverified_emails: false
para.security.admins_have_full_api_```

**Comment by jmakanjuola** [comment]
Here is my entire log

```2018-11-06 20:53:04 [31m[WARN ][0;39m Para configuration file 'application.(conf|json|properties)' is missing from classpath.
                          __    __
   ______________  ____  / /___/ /
  / ___/ ___/ __ \/ __ \/ / __  /
 (__  ) /__/ /_/ / /_/ / / /_/ /
/____/\___/\____/\____/_/\__,_/     (v1.31.0)

2018-11-06 20:53:05 [34m[INFO ][0;39m Starting ScooldServer v1.31.0 on scoold-66df744d46-7n25j with PID 1 (/scoold/scoold-1.31.0.jar started by scoold in /scoold)
2018-11-06 20:53:05 [34m[INFO ][0;39m The following profiles are active: embedded
2018-11-06 20:53:08 [34m[INFO ][0;39m Listening on port 8000...
2018-11-06 20:53:08 [31m[WARN ][0;39m Secret key appears to be invalid. Make sure you call 'signIn()' first.
2018-11-06 20:53:11 [1;31m[ERROR][0;39m No connection to Para backend - make sure that your keys are valid.
2018-11-06 20:53:11 [34m[INFO ][0;39m Default language map not set, loading English.
2018-11-06 20:53:11 [34m[INFO ][0;39m SpringResourceLoader for Velocity: using resource loader [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2c6a3f77: startup date [Tue Nov 06 20:53:05 GMT 2018]; root of context hierarchy] and resource loader paths [classpath:templates/]
2018-11-06 20```

**Comment by albogdano** [comment]
Well, yeah, as I said your Scoold config file is not even loaded. It must be on the Java classpath. If you put it in `/etc/scoold` be sure to start Scoold with `-Dconfig.file=/etc/scoold/application.conf`.

**Comment by jmakanjuola** [comment]
Hello @albogdano  I don't think that Java is the issue here. Java is obviously running. The could be a bug in your codebase or the documents is totally off ```kubectl exec -it scoold-66df744d46-7n25j /bin/sh -n scoold
/scoold $ ps aux | grep java
    1 scoold    0:17 java -Dconfig.file=/etc/scoold/application.conf -Djava.security.egd=file:/dev/./urandom -jar scoold-1.31.0.jar
   38 scoold    0:00 grep java```

**Comment by jmakanjuola** [comment]
> Well, yeah, as I said your Scoold config file is not even loaded. It should be on the Java classpath. If you put it in `/etc/scoold` be sure to start Scoold with `-Dconfig.file=/etc/scoold/application.conf`.

▶ Hello @albogdano I don't think that Java is the issue here. Java is obviously running. The could be a bug in your codebase or the documents is totally off. This issue has not been resolved.

▶  /scoold $ ps aux | grep java
    1 scoold    0:17 java -Dconfig.file=/etc/scoold/application.conf -Djava.security.egd=file:/dev/./urandom -jar scoold-1.31.0.jar
   38 scoold    0:00 grep java```

**Comment by albogdano** [comment]
I wasn't talking about Java itself but the Java classpath. If Scoold isn't connecting to the Para backend you obviously have a problem with configuration.
